/**
 * Module variables
 *
 * @format
 */

const sections = [
	{
		name: 'login',
		paths: [ '/login' ],
		module: 'login',
		group: 'login',
		secondary: false,
		enableLoggedOut: true,
		isomorphic: true,
	},
	// {
	// 	name: 'me',
	// 	paths: [ '/me' ],
	// 	module: 'me',
	// 	group: 'me',
	// 	secondary: true,
	// 	css: 'dashboard',
	// },
	// {
	// 	name: 'create-site',
	// 	paths: [ '/sites/create' ],
	// 	module: 'create-site',
	// 	group: 'sites',
	// 	secondary: false,
	// 	css: 'create-site',
	// },
	// {
	// 	name: 'dashboard',
	// 	paths: [ '/dashboard' ],
	// 	module: 'dashboard',
	// 	group: 'dashboard',
	// 	secondary: true,
	// 	css: 'dashboard',
	// },
	// {
	// 	name: 'dashboard-stats',
	// 	paths: [ '/dashboard/stats' ],
	// 	module: 'dashboard',
	// 	group: 'dashboard',
	// 	secondary: true,
	// 	css: 'dashboard',
	// },
	// {
	// 	name: 'dashboard-orders',
	// 	paths: [ '/dashboard/orders' ],
	// 	module: 'dashboard/orders',
	// 	group: 'dashboard',
	// 	secondary: true,
	// 	css: 'dashboard',
	// },
	// {
	// 	name: 'dashboard-products',
	// 	paths: [ '/dashboard/products' ],
	// 	module: 'dashboard/products',
	// 	secondary: true,
	// 	group: 'dashboard',
	// 	css: 'dashboard',
	// },
	// {
	// 	name: 'dashboard-media',
	// 	paths: [ '/dashboard/media' ],
	// 	module: 'dashboard/media',
	// 	group: 'dashboard',
	// 	secondary: true,
	// 	css: 'media',
	// },
	// {
	// 	name: 'dashboard-people',
	// 	paths: [ '/dashboard/people' ],
	// 	module: 'dashboard/people',
	// 	secondary: true,
	// 	group: 'dashboard',
	// },
	// {
	// 	name: 'accept-invite',
	// 	paths: [ '/accept-invite' ],
	// 	module: 'dashboard/invites',
	// 	enableLoggedOut: true,
	// },
	// {
	// 	name: 'stats',
	// 	paths: [ '/dashboard/stats' ],
	// 	module: 'dashboard/stats',
	// 	secondary: true,
	// 	group: 'dashboard',
	// },
	// {
	// 	name: 'settings',
	// 	paths: [ '/dashboard/settings' ],
	// 	module: 'dashboard/site-settings',
	// 	secondary: true,
	// 	group: 'dashboard',
	// 	css: 'site-settings',
	// },
	// {
	// 	name: 'telesale',
	// 	paths: [ '/orders' ],
	// 	module: 'telesale',
	// 	group: 'telesale',
	// 	secondary: true,
	// 	wideSecondary: true,
	// 	css: 'telesale',
	// },
	{
		name: 'create-team',
		paths: [ '/teams/create' ],
		module: 'create-team',
		group: 'teams',
		secondary: false,
		css: 'create-team',
		isFluidWidth: true,
	},
	{
		name: 'no-team',
		paths: [ '/teams/noteam' ],
		module: 'create-team',
		group: 'teams',
		secondary: false,
		css: 'create-team',
		isFluidWidth: true,
	},
	{
		name: 'select-team',
		paths: [ '/teams/select' ],
		module: 'create-team',
		group: 'teams',
		secondary: false,
		css: 'create-team',
		isFluidWidth: true,
	},
	{
		name: 'select-pages',
		paths: [ '/pages/select' ],
		module: 'select-pages',
		group: 'pages',
		secondary: false,
		css: 'select-pages',
		isFluidWidth: true,
	},
	{
		name: 'conversations',
		paths: [ '/conversations' ],
		module: 'conversations',
		group: 'conversations',
		secondary: true,
		css: 'conversations',
		isFluidWidth: true,
	},
	{
		name: 'conversations',
		paths: [ '/conversations/m' ],
		module: 'conversations',
		group: 'conversations',
		secondary: true,
		css: 'conversations',
		isFluidWidth: true,
	},
	{
		name: 'admin',
		paths: [ '/admin' ],
		module: 'admin',
		group: 'admin',
		secondary: true,
		css: 'admin',
		isFluidWidth: true,
	},
	{
		name: 'admin-members',
		paths: [ '/admin/members' ],
		module: 'admin/members',
		secondary: true,
		group: 'admin',
		isFluidWidth: true,
	},
	{
		name: 'admin-orders',
		paths: [ '/admin/orders' ],
		module: 'admin/orders',
		group: 'admin',
		secondary: true,
		css: 'admin-orders',
		isFluidWidth: true,
	},
];

// sections.push( {
// 	name: 'post-editor',
// 	paths: [ '/order', '/page', '/edit' ],
// 	module: 'post-editor',
// 	group: 'editor',
// 	secondary: true,
// 	css: 'post-editor',
// } );

// sections.push( {
// 	name: 'oauthlogin',
// 	paths: [ '/log-in' ],
// 	module: 'oauth-login',
// 	enableLoggedOut: true,
// 	// isomorphic: true,
// 	secondary: false,
// 	css: 'login',
// } );

// sections.push( {
// 	name: 'comments',
// 	paths: [ '/dashboard/comments', '/dashboard/comment' ],
// 	module: 'dashboard/comments',
// 	group: 'dashboard',
// 	secondary: true,
// 	css: 'comments',
// } );

module.exports = sections;
