export const SocketEvents = {
	POSTED: 'posted',
	POST_EDITED: 'post_edited',
	POST_DELETED: 'post_deleted',
	POST_UPDATED: 'post_updated',
	CHANNEL_CONVERTED: 'channel_converted',
	CHANNEL_CREATED: 'channel_created',
	CHANNEL_DELETED: 'channel_deleted',
	CHANNEL_UPDATED: 'channel_updated',
	CHANNEL_VIEWED: 'channel_viewed',
	CHANNEL_MEMBER_UPDATED: 'channel_member_updated',
	DIRECT_ADDED: 'direct_added',
	NEW_USER: 'new_user',
	ADDED_TO_TEAM: 'added_to_team',
	JOIN_TEAM: 'join_team',
	LEAVE_TEAM: 'leave_team',
	UPDATE_TEAM: 'update_team',
	DELETE_TEAM: 'delete_team',
	USER_ADDED: 'user_added',
	USER_REMOVED: 'user_removed',
	USER_UPDATED: 'user_updated',
	USER_ROLE_UPDATED: 'user_role_updated',
	MEMBERROLE_UPDATED: 'memberrole_updated',
	ROLE_ADDED: 'role_added',
	ROLE_REMOVED: 'role_removed',
	ROLE_UPDATED: 'role_updated',
	TYPING: 'typing',
	PREFERENCE_CHANGED: 'preference_changed',
	PREFERENCES_CHANGED: 'preferences_changed',
	PREFERENCES_DELETED: 'preferences_deleted',
	EPHEMERAL_MESSAGE: 'ephemeral_message',
	STATUS_CHANGED: 'status_change',
	HELLO: 'hello',
	REACTION_ADDED: 'reaction_added',
	REACTION_REMOVED: 'reaction_removed',
	EMOJI_ADDED: 'emoji_added',
	PLUGIN_ENABLED: 'plugin_enabled',
	PLUGIN_DISABLED: 'plugin_disabled',
	LICENSE_CHANGED: 'license_changed',
	CONFIG_CHANGED: 'config_changed',
	PLUGIN_STATUSES_CHANGED: 'plugin_statuses_changed',

	CONVERSATION_UNSEEN: 'conversation_unseen',
	CONVERSATION_SEEN: 'conversation_seen',
	CONVERSATION_RECEIVED_TAG: 'conversation_received_tag',
	CONVERSATION_REMOVED_TAG: 'conversation_removed_tag',
	PAGE_RECEIVED_TAG: 'page_tag_created',

	RECEIVE_CONVERSATION_UPDATED: 'receive_conversation_update',
	RECEIVE_COMMENT_UPDATED: 'receive_comment_update',
	RECEIVE_PAGE_STATUS_UPDATED: 'page_status_updated',
	RECEIVE_PAGES_STATUS_UPDATED: 'pages_status_updated',

	RECEIVE_PAGES_INIT_VALIDATION_RESULT: 'pages_init_validation_result',
	RECEIVE_PAGES_INIT_VALUE: 'pages_init_update_value',

	CONVERSATION_ADD_MESSAGE: 'conversation_add_message',
	MESSAGE_SENT: 'message_sent',
	CONVERSATION_READ: 'read_watermark',

	// orders
	ADDED_ORDER: 'added_order',
};

export const Constants = {
	IMAGE_TYPE_GIF: 'gif',
	IMAGE_TYPES: [ 'jpg', 'gif', 'bmp', 'png', 'jpeg' ],
	AUDIO_TYPES: [ 'mp3', 'wav', 'wma', 'm4a', 'flac', 'aac', 'ogg', 'm4r' ],
	VIDEO_TYPES: [ 'mp4', 'avi', 'webm', 'mkv', 'wmv', 'mpg', 'mov', 'flv' ],
	PRESENTATION_TYPES: [ 'ppt', 'pptx' ],
	SPREADSHEET_TYPES: [ 'xlsx', 'csv' ],
	WORD_TYPES: [ 'doc', 'docx' ],
	CODE_TYPES: [
		'applescript',
		'as',
		'atom',
		'bas',
		'bash',
		'boot',
		'c',
		'c++',
		'cake',
		'cc',
		'cjsx',
		'cl2',
		'clj',
		'cljc',
		'cljs',
		'cljs.hl',
		'cljscm',
		'cljx',
		'_coffee',
		'coffee',
		'cpp',
		'cs',
		'csharp',
		'cson',
		'css',
		'd',
		'dart',
		'delphi',
		'dfm',
		'di',
		'diff',
		'django',
		'docker',
		'dockerfile',
		'dpr',
		'erl',
		'ex',
		'exs',
		'f90',
		'f95',
		'freepascal',
		'fs',
		'fsharp',
		'gcode',
		'gemspec',
		'go',
		'groovy',
		'gyp',
		'h',
		'h++',
		'handlebars',
		'hbs',
		'hic',
		'hpp',
		'hs',
		'html',
		'html.handlebars',
		'html.hbs',
		'hx',
		'iced',
		'irb',
		'java',
		'jinja',
		'jl',
		'js',
		'json',
		'jsp',
		'jsx',
		'kt',
		'ktm',
		'kts',
		'lazarus',
		'less',
		'lfm',
		'lisp',
		'log',
		'lpr',
		'lua',
		'm',
		'mak',
		'matlab',
		'md',
		'mk',
		'mkd',
		'mkdown',
		'ml',
		'mm',
		'nc',
		'obj-c',
		'objc',
		'osascript',
		'pas',
		'pascal',
		'perl',
		'php',
		'php3',
		'php4',
		'php5',
		'php6',
		'pl',
		'plist',
		'podspec',
		'pp',
		'ps',
		'ps1',
		'py',
		'r',
		'rb',
		'rs',
		'rss',
		'ruby',
		'scala',
		'scm',
		'scpt',
		'scss',
		'sh',
		'sld',
		'sql',
		'st',
		'styl',
		'swift',
		'tex',
		'thor',
		'txt',
		'v',
		'vb',
		'vbnet',
		'vbs',
		'veo',
		'xhtml',
		'xml',
		'xsl',
		'yaml',
		'zsh',
	],
	PDF_TYPES: [ 'pdf' ],
	PATCH_TYPES: [ 'patch' ],
	SVG_TYPES: [ 'svg' ],
	ICON_FROM_TYPE: {
		audio: '/papo/images/file-types/icons/audio.svg',
		video: '/papo/images/file-types/icons/video.svg',
		spreadsheet: '/papo/images/file-types/icons/excel.svg',
		presentation: '/papo/images/file-types/icons/ppt.svg',
		pdf: '/papo/images/file-types/icons/pdf.svg',
		code: '/papo/images/file-types/icons/code.svg',
		word: '/papo/images/file-types/icons/word.svg',
		patch: '/papo/images/file-types/icons/patch.png',
		other: '/papo/images/file-types/icons/generic.svg',
	},
	ICON_NAME_FROM_TYPE: {
		audio: 'audio',
		video: 'video',
		spreadsheet: 'excel',
		presentation: 'ppt',
		pdf: 'pdf',
		code: 'code',
		word: 'word',
		patch: 'patch',
		other: 'generic',
		image: 'image',
	},
	MAX_UPLOAD_FILES: 5,
	MAX_FILENAME_LENGTH: 35,
	THUMBNAIL_WIDTH: 150,
	THUMBNAIL_HEIGHT: 150,

	EMOJI_SIZE: 16,
	DEFAULT_EMOJI_PICKER_LEFT_OFFSET: 87,
	DEFAULT_EMOJI_PICKER_RIGHT_OFFSET: 15,
	EMOJI_PICKER_WIDTH_OFFSET: 295,

	KeyCodes: {
		BACKSPACE: [ 'Backspace', 8 ],
		TAB: [ 'Tab', 9 ],
		ENTER: [ 'Enter', 13 ],
		SHIFT: [ 'Shift', 16 ],
		CTRL: [ 'Control', 17 ],
		ALT: [ 'Alt', 18 ],
		CAPS_LOCK: [ 'CapsLock', 20 ],
		ESCAPE: [ 'Escape', 27 ],
		SPACE: [ ' ', 32 ],
		PAGE_UP: [ 'PageUp', 33 ],
		PAGE_DOWN: [ 'PageDown', 34 ],
		END: [ 'End', 35 ],
		HOME: [ 'Home', 36 ],
		LEFT: [ 'ArrowLeft', 37 ],
		UP: [ 'ArrowUp', 38 ],
		RIGHT: [ 'ArrowRight', 39 ],
		DOWN: [ 'ArrowDown', 40 ],
		INSERT: [ 'Insert', 45 ],
		DELETE: [ 'Delete', 46 ],
		ZERO: [ '0', 48 ],
		ONE: [ '1', 49 ],
		TWO: [ '2', 50 ],
		THREE: [ '3', 51 ],
		FOUR: [ '4', 52 ],
		FIVE: [ '5', 53 ],
		SIX: [ '6', 54 ],
		SEVEN: [ '7', 55 ],
		EIGHT: [ '8', 56 ],
		NINE: [ '9', 57 ],
		A: [ 'a', 65 ],
		B: [ 'b', 66 ],
		C: [ 'c', 67 ],
		D: [ 'd', 68 ],
		E: [ 'e', 69 ],
		F: [ 'f', 70 ],
		G: [ 'g', 71 ],
		H: [ 'h', 72 ],
		I: [ 'i', 73 ],
		J: [ 'j', 74 ],
		K: [ 'k', 75 ],
		L: [ 'l', 76 ],
		M: [ 'm', 77 ],
		N: [ 'n', 78 ],
		O: [ 'o', 79 ],
		P: [ 'p', 80 ],
		Q: [ 'q', 81 ],
		R: [ 'r', 82 ],
		S: [ 's', 83 ],
		T: [ 't', 84 ],
		U: [ 'u', 85 ],
		V: [ 'v', 86 ],
		W: [ 'w', 87 ],
		X: [ 'x', 88 ],
		Y: [ 'y', 89 ],
		Z: [ 'z', 90 ],
		CMD: [ 'Meta', 91 ],
		MENU: [ 'ContextMenu', 93 ],
		NUMPAD_0: [ '0', 96 ],
		NUMPAD_1: [ '1', 97 ],
		NUMPAD_2: [ '2', 98 ],
		NUMPAD_3: [ '3', 99 ],
		NUMPAD_4: [ '4', 100 ],
		NUMPAD_5: [ '5', 101 ],
		NUMPAD_6: [ '6', 102 ],
		NUMPAD_7: [ '7', 103 ],
		NUMPAD_8: [ '8', 104 ],
		NUMPAD_9: [ '9', 105 ],
		MULTIPLY: [ '*', 106 ],
		ADD: [ '+', 107 ],
		SUBTRACT: [ '-', 109 ],
		DECIMAL: [ '.', 110 ],
		DIVIDE: [ '/', 111 ],
		F1: [ 'F1', 112 ],
		F2: [ 'F2', 113 ],
		F3: [ 'F3', 114 ],
		F4: [ 'F4', 115 ],
		F5: [ 'F5', 116 ],
		F6: [ 'F6', 117 ],
		F7: [ 'F7', 118 ],
		F8: [ 'F8', 119 ],
		F9: [ 'F9', 120 ],
		F10: [ 'F10', 121 ],
		F11: [ 'F11', 122 ],
		F12: [ 'F12', 123 ],
		NUM_LOCK: [ 'NumLock', 144 ],
		SEMICOLON: [ ';', 186 ],
		EQUAL: [ '=', 187 ],
		COMMA: [ ',', 188 ],
		DASH: [ '-', 189 ],
		PERIOD: [ '.', 190 ],
		FORWARD_SLASH: [ '/', 191 ],
		TILDE: [ '~', 192 ], // coudnt find the key or even get code from browser - no reference in code as of now
		OPEN_BRACKET: [ '[', 219 ],
		BACK_SLASH: [ '\\', 220 ],
		CLOSE_BRACKET: [ ']', 221 ],
		COMPOSING: [ 'Composing', 229 ],
	},
	TAG_COLORS: [
		'#e6194b',
		'#3cb44b',
		'#ffe119',
		'#4363d8',
		'#f58231',
		'#911eb4',
		'#46f0f0',
		'#f032e6',
		'#bcf60c',
		'#fabebe',
		'#008080',
		'#e6beff',
		'#9a6324',
		'#fffac8',
		'#800000',
		'#aaffc3',
		'#808000',
		'#ffd8b1',
		'#000075',
		'#808080',
		'#F7412C',
		'#9D1DB2',
		'#6834BC',
		'#3F4DB8',
		'#0B95F7',
		'#009788',
		'#48B14C',
		'#FF5608',
		'#7B5548',
		'#9E9E9E',
		'#607D8D',
		'#111111',
		'#ffff00',
		'#001f3f',
		'#85144b',
		'#00ff70',
	],
};

export const FileTypes = {
	IMAGE: 'image',
	AUDIO: 'audio',
	VIDEO: 'video',
	SPREADSHEET: 'spreadsheet',
	CODE: 'code',
	WORD: 'word',
	PRESENTATION: 'presentation',
	PDF: 'pdf',
	PATCH: 'patch',
	SVG: 'svg',
	OTHER: 'other',
};

export default Constants;
