// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

import keyMirror from 'key-mirror';

export default keyMirror( {
	MESSAGE_LIST_SCROLL_CHANGE: null,
	CLEAR_SNIPPET_CREATE_FORM: null,
	CLEAR_AUTO_MESSAGE_TASK_CREATE_FORM: null,
	BROWSER_CHANGE_FOCUS: null,
	CREATE_PAGE_TAG_SUCCESS: null,
	CONVERSATION_MESSAGES_LOADED: null,
	CONVERSATION_MESSAGES_MORE_LOADED: null,
	SET_SELECTED_PAGES_SUCCESS: null,
	CONVERSATIONS_LOADED: null,
	UPDATE_COMPOSER_SUGGESTION_DISPLAY: null,
	PENDING_MESSAGE_SUBMITED: null,
	CONVERSATION_NOTE_CREATED: null,
	TEAM_CREATE_STATUS: null,

	CREATE_TEAM_ROLE_SUCCESS: null,
	UPDATE_TEAM_ROLE_SUCCESS: null,

	LOADED_FILE_INFOS_SUCCESS: null,
	LOADED_MORE_FILE_INFOS_SUCCESS: null,
} );
