/** @format */
/**
 * Any new action type should be added to the set of exports below, with the
 * value mirroring its exported name.
 *
 * Please keep this list alphabetized!
 *
 * Unsure how to name an action type? Refer to our guidelines:
 *  - https://wpcalypso.wordpress.com/devdocs/docs/our-approach-to-data.md#actions
 */

export const PAGE_LOADING_STATUS = 'PAGE_LOADING_STATUS';
export const MODULE_LOADING_STATUS = 'MODULE_LOADING_STATUS';
export const SET_MODULE_LOADING_TEXT = 'SET_MODULE_LOADING_TEXT';

export const RECEIVED_TEAM = 'RECEIVED_TEAM';
export const REQUEST_MY_TEAMS = 'REQUEST_MY_TEAMS';
export const RECEIVED_MY_TEAMS = 'RECEIVED_MY_TEAMS';
export const FETCH_TEAMS_FAILURED = 'FETCH_TEAMS_FAILURED';
export const FETCH_MY_TEAMS = 'FETCH_MY_TEAMS';
export const REQUEST_TEAM_MEMBERS = 'SET_SELECTED_TEAM';
export const SET_SELECTED_TEAM = 'SET_SELECTED_TEAM';
export const REQUEST_TEAM_MEMBERS_FAILURED = 'SET_SELECTED_TEAM';
export const RECEIVED_TEAM_MEMBERS = 'SET_SELECTED_TEAM';

export const REQUEST_TEAM_ROLES = 'REQUEST_TEAM_ROLES';
export const RECEIVED_TEAM_ROLES = 'RECEIVED_TEAM_ROLES';
export const REQUEST_TEAM_ROLES_FAILURED = 'REQUEST_TEAM_ROLES_FAILURED';
export const REQUEST_TEAM_ROLES_SUCCESS = 'REQUEST_TEAM_ROLES_SUCCESS';

export const RECEIVED_PERMISSIONS = 'RECEIVED_PERMISSIONS';
export const REQUEST_PERMISSIONS_FAILURED = 'REQUEST_PERMISSIONS_FAILURED';

export const CREATE_TEAM_ROLE = 'CREATE_TEAM_ROLE';
export const TEAM_ROLE_CREATED = 'TEAM_ROLE_CREATED';
export const CREATE_TEAM_ROLE_FAILURED = 'CREATE_TEAM_ROLE_FAILURED';
export const RECEIVED_TEAM_ROLE = 'RECEIVED_TEAM_ROLE';

export const UPDATE_TEAM_ROLE = 'UPDATE_TEAM_ROLE';
export const TEAM_ROLE_UPDATED = 'TEAM_ROLE_UPDATED';
export const RECEIVED_TEAM_ROLE_UPDATED = 'RECEIVED_TEAM_ROLE_UPDATED';
export const UPDATE_TEAM_ROLE_FAILURED = 'UPDATE_TEAM_ROLE_FAILURED';

export const ADD_TEAM_MEMBER = 'ADD_TEAM_MEMBER';
export const ADD_TEAM_MEMBER_SUCCESS = 'ADD_TEAM_MEMBER_SUCCESS';
export const ADD_TEAM_MEMBER_FAILURED = 'ADD_TEAM_MEMBER_FAILURED';

// export const UPDATE_TEAM_MEMBER = 'UPDATE_TEAM_MEMBER';
// export const UPDATE_TEAM_MEMBER_SUCCESS = 'UPDATE_TEAM_MEMBER_SUCCESS';
// export const UPDATE_TEAM_MEMBER_FAILURED = 'UPDATE_TEAM_MEMBER_FAILURED';

export const TOGGLE_SHOW_SWITCH_PAGES = 'TOGGLE_SHOW_SWITCH_PAGES';
export const REQUEST_PERMISSIONS = 'REQUEST_PERMISSIONS';

//  █████╗
// ██╔══██╗
// ███████║
// ██╔══██║       ACTIONS START WITH "A"
// ██║  ██║
// ╚═╝  ╚═╝

export const APPLY_STORED_STATE = 'APPLY_STORED_STATE';

// export const ACCOUNT_RECOVERY_RESET_OPTIONS_ERROR = 'ACCOUNT_RECOVERY_RESET_OPTIONS_ERROR';
// export const ACCOUNT_RECOVERY_RESET_OPTIONS_RECEIVE = 'ACCOUNT_RECOVERY_RESET_OPTIONS_RECEIVE';
// export const ACCOUNT_RECOVERY_RESET_OPTIONS_REQUEST = 'ACCOUNT_RECOVERY_RESET_OPTIONS_REQUEST';
// export const ACCOUNT_RECOVERY_RESET_PASSWORD_REQUEST = 'ACCOUNT_RECOVERY_RESET_PASSWORD_REQUEST';
// export const ACCOUNT_RECOVERY_RESET_PASSWORD_REQUEST_ERROR =
// 	'ACCOUNT_RECOVERY_RESET_PASSWORD_REQUEST_ERROR';
// export const ACCOUNT_RECOVERY_RESET_PASSWORD_REQUEST_SUCCESS =
// 	'ACCOUNT_RECOVERY_RESET_PASSWORD_REQUEST_SUCCESS';
// export const ACCOUNT_RECOVERY_RESET_REQUEST = 'ACCOUNT_RECOVERY_RESET_REQUEST';
// export const ACCOUNT_RECOVERY_RESET_REQUEST_ERROR = 'ACCOUNT_RECOVERY_RESET_REQUEST_ERROR';
// export const ACCOUNT_RECOVERY_RESET_REQUEST_SUCCESS = 'ACCOUNT_RECOVERY_RESET_REQUEST_SUCCESS';
// export const ACCOUNT_RECOVERY_RESET_SET_METHOD = 'ACCOUNT_RECOVERY_RESET_SET_METHOD';
// export const ACCOUNT_RECOVERY_RESET_SET_VALIDATION_KEY =
// 	'ACCOUNT_RECOVERY_RESET_SET_VALIDATION_KEY';
// export const ACCOUNT_RECOVERY_RESET_UPDATE_USER_DATA = 'ACCOUNT_RECOVERY_RESET_UPDATE_USER_DATA';
// export const ACCOUNT_RECOVERY_RESET_VALIDATE_REQUEST = 'ACCOUNT_RECOVERY_RESET_VALIDATE_REQUEST';
// export const ACCOUNT_RECOVERY_RESET_VALIDATE_REQUEST_ERROR =
// 	'ACCOUNT_RECOVERY_RESET_VALIDATE_REQUEST_ERROR';
// export const ACCOUNT_RECOVERY_RESET_VALIDATE_REQUEST_SUCCESS =
// 	'ACCOUNT_RECOVERY_RESET_VALIDATE_REQUEST_SUCCESS';
// export const ACCOUNT_RECOVERY_SETTINGS_DELETE = 'ACCOUNT_RECOVERY_SETTINGS_DELETE';
// export const ACCOUNT_RECOVERY_SETTINGS_DELETE_FAILED = 'ACCOUNT_RECOVERY_SETTINGS_DELETE_FAILED';
// export const ACCOUNT_RECOVERY_SETTINGS_DELETE_SUCCESS = 'ACCOUNT_RECOVERY_SETTINGS_DELETE_SUCCESS';
// export const ACCOUNT_RECOVERY_SETTINGS_FETCH = 'ACCOUNT_RECOVERY_SETTINGS_FETCH';
// export const ACCOUNT_RECOVERY_SETTINGS_FETCH_FAILED = 'ACCOUNT_RECOVERY_SETTINGS_FETCH_FAILED';
// export const ACCOUNT_RECOVERY_SETTINGS_FETCH_SUCCESS = 'ACCOUNT_RECOVERY_SETTINGS_FETCH_SUCCESS';
// export const ACCOUNT_RECOVERY_SETTINGS_RESEND_VALIDATION =
// 	'ACCOUNT_RECOVERY_SETTINGS_RESEND_VALIDATION';
// export const ACCOUNT_RECOVERY_SETTINGS_RESEND_VALIDATION_FAILED =
// 	'ACCOUNT_RECOVERY_SETTINGS_RESEND_VALIDATION_FAILED';
// export const ACCOUNT_RECOVERY_SETTINGS_RESEND_VALIDATION_SUCCESS =
// 	'ACCOUNT_RECOVERY_SETTINGS_RESEND_VALIDATION_SUCCESS';
// export const ACCOUNT_RECOVERY_SETTINGS_UPDATE = 'ACCOUNT_RECOVERY_SETTINGS_UPDATE';
// export const ACCOUNT_RECOVERY_SETTINGS_UPDATE_FAILED = 'ACCOUNT_RECOVERY_SETTINGS_UPDATE_FAILED';
// export const ACCOUNT_RECOVERY_SETTINGS_UPDATE_SUCCESS = 'ACCOUNT_RECOVERY_SETTINGS_UPDATE_SUCCESS';
// export const ACCOUNT_RECOVERY_SETTINGS_VALIDATE_PHONE = 'ACCOUNT_RECOVERY_SETTINGS_VALIDATE_PHONE';
// export const ACCOUNT_RECOVERY_SETTINGS_VALIDATE_PHONE_FAILED =
// 	'ACCOUNT_RECOVERY_SETTINGS_VALIDATE_PHONE_FAILED';
// export const ACCOUNT_RECOVERY_SETTINGS_VALIDATE_PHONE_SUCCESS =
// 	'ACCOUNT_RECOVERY_SETTINGS_VALIDATE_PHONE_SUCCESS';
// export const ACTIVE_THEME_REQUEST = 'ACTIVE_THEME_REQUEST';
// export const ACTIVE_THEME_REQUEST_FAILURE = 'ACTIVE_THEME_REQUEST_FAILURE';
// export const ACTIVE_THEME_REQUEST_SUCCESS = 'ACTIVE_THEME_REQUEST_SUCCESS';
// export const ACTIVITY_LOG_REQUEST = 'ACTIVITY_LOG_REQUEST';
// export const ACTIVITY_LOG_UPDATE = 'ACTIVITY_LOG_UPDATE';
// export const ACTIVITY_LOG_WATCH = 'ACTIVITY_LOG_WATCH';
// export const AFFILIATE_REFERRAL = 'AFFILIATE_REFERRAL';
// export const ANALYTICS_EVENT_RECORD = 'ANALYTICS_EVENT_RECORD';
// export const ANALYTICS_MULTI_TRACK = 'ANALYTICS_MULTI_TRACK';
// export const ANALYTICS_PAGE_VIEW_RECORD = 'ANALYTICS_PAGE_VIEW_RECORD';
// export const ANALYTICS_STAT_BUMP = 'ANALYTICS_STAT_BUMP';
// export const ANALYTICS_SUPER_PROPS_UPDATE = 'ANALYTICS_SUPER_PROPS_UPDATE';
// export const ANALYTICS_TRACKS_ANONID_SET = 'ANALYTICS_TRACKS_ANONID_SET';
// export const ANALYTICS_TRACKING_ON = 'ANALYTICS_TRACKING_ON';
// export const ANALYTICS_TRACKS_OPT_OUT = 'ANALYTICS_TRACKS_OPT_OUT';
// export const AUTOMATED_TRANSFER_ELIGIBILITY_REQUEST = 'AUTOMATED_TRANSFER_ELIGIBILITY_REQUEST';
// export const AUTOMATED_TRANSFER_ELIGIBILITY_UPDATE = 'AUTOMATED_TRANSFER_ELIGIBILITY_UPDATE';
// export const AUTOMATED_TRANSFER_INITIATE_WITH_PLUGIN_ZIP =
// 	'AUTOMATED_TRANSFER_INITIATE_WITH_PLUGIN_ZIP';
// export const AUTOMATED_TRANSFER_STATUS_REQUEST = 'AUTOMATED_TRANSFER_STATUS_REQUEST';
// export const AUTOMATED_TRANSFER_STATUS_REQUEST_FAILURE =
// 	'AUTOMATED_TRANSFER_STATUS_REQUEST_FAILURE';
// export const AUTOMATED_TRANSFER_STATUS_SET = 'AUTOMATED_TRANSFER_STATUS_SET';

// ██████╗
// ██╔══██╗
// ██████╔╝       ACTIONS START WITH "B"
// ██╔══██╗
// ██████╔╝
// ╚═════╝

// export const BILLING_RECEIPT_EMAIL_SEND = 'BILLING_RECEIPT_EMAIL_SEND';
// export const BILLING_RECEIPT_EMAIL_SEND_FAILURE = 'BILLING_RECEIPT_EMAIL_SEND_FAILURE';
// export const BILLING_RECEIPT_EMAIL_SEND_SUCCESS = 'BILLING_RECEIPT_EMAIL_SEND_SUCCESS';
// export const BILLING_TRANSACTIONS_RECEIVE = 'BILLING_TRANSACTIONS_RECEIVE';
// export const BILLING_TRANSACTIONS_REQUEST = 'BILLING_TRANSACTIONS_REQUEST';
// export const BILLING_TRANSACTIONS_REQUEST_FAILURE = 'BILLING_TRANSACTIONS_REQUEST_FAILURE';
// export const BILLING_TRANSACTIONS_REQUEST_SUCCESS = 'BILLING_TRANSACTIONS_REQUEST_SUCCESS';
// export const CONCIERGE_APPOINTMENT_CANCEL = 'CONCIERGE_APPOINTMENT_CANCEL';
// export const CONCIERGE_APPOINTMENT_CREATE = 'CONCIERGE_APPOINTMENT_CREATE';
// export const CONCIERGE_APPOINTMENT_DETAILS_REQUEST = 'CONCIERGE_APPOINTMENT_DETAILS_REQUEST';
// export const CONCIERGE_APPOINTMENT_DETAILS_UPDATE = 'CONCIERGE_APPOINTMENT_DETAILS_UPDATE';
// export const CONCIERGE_APPOINTMENT_RESCHEDULE = 'CONCIERGE_APPOINTMENT_RESCHEDULE';
// export const CONCIERGE_AVAILABLE_TIMES_REQUEST = 'CONCIERGE_AVAILABLE_TIMES_REQUEST';
// export const CONCIERGE_AVAILABLE_TIMES_UPDATE = 'CONCIERGE_AVAILABLE_TIMES_UPDATE';
// export const CONCIERGE_SIGNUP_FORM_UPDATE = 'CONCIERGE_SIGNUP_FORM_UPDATE';
// export const CONCIERGE_UPDATE_BOOKING_STATUS = 'CONCIERGE_UPDATE_BOOKING_STATUS';
// export const COMMENT_COUNTS_UPDATE = 'COMMENT_COUNTS_UPDATE';
// export const COMMENT_COUNTS_REQUEST = 'COMMENT_COUNTS_REQUEST';
// export const COMMENT_REQUEST = 'COMMENT_REQUEST';
// export const COMMENTS_CHANGE_STATUS = 'COMMENTS_CHANGE_STATUS';
// export const COMMENTS_COUNT_INCREMENT = 'COMMENTS_COUNT_INCREMENT';
// export const COMMENTS_COUNT_RECEIVE = 'COMMENTS_COUNT_RECEIVE';
// export const COMMENTS_DELETE = 'COMMENTS_DELETE';
// export const COMMENTS_EDIT = 'COMMENTS_EDIT';
// export const COMMENTS_LIKE = 'COMMENTS_LIKE';
// export const COMMENTS_LIST_REQUEST = 'COMMENTS_LIST_REQUEST';
// export const COMMENTS_QUERY_UPDATE = 'COMMENTS_QUERY_UPDATE';
// export const COMMENTS_RECEIVE = 'COMMENTS_RECEIVE';
// export const COMMENTS_RECEIVE_ERROR = 'COMMENTS_RECEIVE_ERROR';
// export const COMMENTS_REPLY_WRITE = 'COMMENTS_REPLY_WRITE';
// export const COMMENTS_REQUEST = 'COMMENTS_REQUEST';
// export const COMMENTS_REQUEST_FAILURE = 'COMMENTS_REQUEST_FAILURE';
// export const COMMENTS_REQUEST_SUCCESS = 'COMMENTS_REQUEST_SUCCESS';
// export const COMMENTS_SET_ACTIVE_REPLY = 'COMMENTS_SET_ACTIVE_REPLY';
// export const COMMENTS_TREE_SITE_ADD = 'COMMENTS_TREE_SITE_ADD';
// export const COMMENTS_TREE_SITE_REQUEST = 'COMMENTS_TREE_SITE_REQUEST';
// export const COMMENTS_UNLIKE = 'COMMENTS_UNLIKE';
// export const COMMENTS_WRITE = 'COMMENTS_WRITE';
// export const COMMENTS_WRITE_ERROR = 'COMMENTS_WRITE_ERROR';
// export const COMPONENTS_USAGE_STATS_RECEIVE = 'COMPONENTS_USAGE_STATS_RECEIVE';
// export const COMPONENTS_USAGE_STATS_REQUEST = 'COMPONENTS_USAGE_STATS_REQUEST';
export const CONNECTION_LOST = 'CONNECTION_LOST';
export const CONNECTION_RESTORED = 'CONNECTION_RESTORED';
// export const COUNTRIES_DOMAINS_FETCH = 'COUNTRIES_DOMAINS_FETCH';
// export const COUNTRIES_DOMAINS_UPDATED = 'COUNTRIES_DOMAINS_UPDATED';
// export const COUNTRIES_PAYMENTS_FETCH = 'COUNTRIES_PAYMENTS_FETCH';
// export const COUNTRIES_PAYMENTS_UPDATED = 'COUNTRIES_PAYMENTS_UPDATED';
// export const COUNTRIES_SMS_FETCH = 'COUNTRIES_SMS_FETCH';
// export const COUNTRIES_SMS_UPDATED = 'COUNTRIES_SMS_UPDATED';
// export const COUNTRY_STATES_RECEIVE = 'COUNTRY_STATES_RECEIVE';
// export const COUNTRY_STATES_REQUEST = 'COUNTRY_STATES_REQUEST';
// export const COUNTRY_STATES_REQUEST_FAILURE = 'COUNTRY_STATES_REQUEST_FAILURE';
// export const COUNTRY_STATES_REQUEST_SUCCESS = 'COUNTRY_STATES_REQUEST_SUCCESS';
// export const CURRENT_USER_FLAGS_RECEIVE = 'CURRENT_USER_FLAGS_RECEIVE';
// export const CURRENT_USER_ID_SET = 'CURRENT_USER_ID_SET';
export const DESERIALIZE = 'DESERIALIZE';
// export const DIRECTLY_ASK_QUESTION = 'DIRECTLY_ASK_QUESTION';
// export const DIRECTLY_INITIALIZATION_ERROR = 'DIRECTLY_INITIALIZATION_ERROR';
// export const DIRECTLY_INITIALIZATION_START = 'DIRECTLY_INITIALIZATION_START';
// export const DIRECTLY_INITIALIZATION_SUCCESS = 'DIRECTLY_INITIALIZATION_SUCCESS';
// export const DOCUMENT_HEAD_LINK_SET = 'DOCUMENT_HEAD_LINK_SET';
// export const DOCUMENT_HEAD_META_SET = 'DOCUMENT_HEAD_META_SET';
// export const DOCUMENT_HEAD_TITLE_SET = 'DOCUMENT_HEAD_TITLE_SET';
// export const DOCUMENT_HEAD_UNREAD_COUNT_SET = 'DOCUMENT_HEAD_UNREAD_COUNT_SET';
// export const DOMAIN_MANAGEMENT_CONTACT_DETAILS_CACHE_RECEIVE =
// 	'DOMAIN_MANAGEMENT_CONTACT_DETAILS_CACHE_RECEIVE';
// export const DOMAIN_MANAGEMENT_CONTACT_DETAILS_CACHE_REQUEST =
// 	'DOMAIN_MANAGEMENT_CONTACT_DETAILS_CACHE_REQUEST';
// export const DOMAIN_MANAGEMENT_CONTACT_DETAILS_CACHE_REQUEST_FAILURE =
// 	'DOMAIN_MANAGEMENT_CONTACT_DETAILS_CACHE_REQUEST_FAILURE';
// export const DOMAIN_MANAGEMENT_CONTACT_DETAILS_CACHE_REQUEST_SUCCESS =
// 	'DOMAIN_MANAGEMENT_CONTACT_DETAILS_CACHE_REQUEST_SUCCESS';
// export const DOMAIN_MANAGEMENT_CONTACT_DETAILS_CACHE_UPDATE =
// 	'DOMAIN_MANAGEMENT_CONTACT_DETAILS_CACHE_UPDATE';
// export const DOMAIN_MANAGEMENT_VALIDATION_SCHEMAS_ADD = 'DOMAIN_MANAGEMENT_VALIDATION_SCHEMAS_ADD';
// export const DOMAIN_MANAGEMENT_VALIDATION_SCHEMAS_REQUEST =
// 	'DOMAIN_MANAGEMENT_VALIDATION_SCHEMAS_REQUEST';
// export const DOMAIN_MANAGEMENT_WHOIS_RECEIVE = 'DOMAIN_MANAGEMENT_WHOIS_RECEIVE';
// export const DOMAIN_MANAGEMENT_WHOIS_REQUEST = 'DOMAIN_MANAGEMENT_WHOIS_REQUEST';
// export const DOMAIN_MANAGEMENT_WHOIS_REQUEST_FAILURE = 'DOMAIN_MANAGEMENT_WHOIS_REQUEST_FAILURE';
// export const DOMAIN_MANAGEMENT_WHOIS_REQUEST_SUCCESS = 'DOMAIN_MANAGEMENT_WHOIS_REQUEST_SUCCESS';
// export const DOMAIN_MANAGEMENT_WHOIS_SAVE = 'DOMAIN_MANAGEMENT_WHOIS_SAVE';
// export const DOMAIN_MANAGEMENT_WHOIS_SAVE_FAILURE = 'DOMAIN_MANAGEMENT_WHOIS_SAVE_FAILURE';
// export const DOMAIN_MANAGEMENT_WHOIS_SAVE_SUCCESS = 'DOMAIN_MANAGEMENT_WHOIS_SAVE_SUCCESS';
// export const DOMAIN_MANAGEMENT_WHOIS_UPDATE = 'DOMAIN_MANAGEMENT_WHOIS_UPDATE';
// export const DOMAINS_SUGGESTIONS_RECEIVE = 'DOMAINS_SUGGESTIONS_RECEIVE';
// export const DOMAINS_SUGGESTIONS_REQUEST = 'DOMAINS_SUGGESTIONS_REQUEST';
// export const DOMAINS_SUGGESTIONS_REQUEST_FAILURE = 'DOMAINS_SUGGESTIONS_REQUEST_FAILURE';
// export const DOMAINS_SUGGESTIONS_REQUEST_SUCCESS = 'DOMAINS_SUGGESTIONS_REQUEST_SUCCESS';
// export const DOMAIN_TRANSFER_IPS_TAG_SAVE = 'DOMAIN_TRANSFER_IPS_TAG_SAVE';
// export const DOMAIN_TRANSFER_UPDATE = 'DOMAIN_TRANSFER_UPDATE';
// export const DROPZONE_HIDE = 'DROPZONE_HIDE';
// export const DROPZONE_SHOW = 'DROPZONE_SHOW';
// export const EDITOR_CONTACT_FORM_CLEAR = 'EDITOR_CONTACT_FORM_CLEAR';
// export const EDITOR_CONTACT_FORM_FIELD_ADD = 'EDITOR_CONTACT_FORM_FIELD_ADD';
// export const EDITOR_CONTACT_FORM_FIELD_REMOVE = 'EDITOR_CONTACT_FORM_FIELD_REMOVE';
// export const EDITOR_CONTACT_FORM_FIELD_UPDATE = 'EDITOR_CONTACT_FORM_FIELD_UPDATE';
// export const EDITOR_CONTACT_FORM_LOAD = 'EDITOR_CONTACT_FORM_LOAD';
// export const EDITOR_CONTACT_FORM_SETTINGS_UPDATE = 'EDITOR_CONTACT_FORM_SETTINGS_UPDATE';
// export const EDITOR_LAST_DRAFT_SET = 'EDITOR_LAST_DRAFT_SET';
// export const EDITOR_MEDIA_EDIT_ITEM_SET = 'EDITOR_MEDIA_EDIT_ITEM_SET';
// export const EDITOR_PASTE_EVENT = 'EDITOR_PASTE_EVENT';
// export const EDITOR_START = 'EDITOR_START';
// export const EDITOR_STOP = 'EDITOR_STOP';
// export const EMAIL_VERIFY_REQUEST = 'EMAIL_VERIFY_REQUEST';
// export const EMAIL_VERIFY_REQUEST_SUCCESS = 'EMAIL_VERIFY_REQUEST_SUCCESS';
// export const EMAIL_VERIFY_REQUEST_FAILURE = 'EMAIL_VERIFY_REQUEST_FAILURE';
// export const EMAIL_VERIFY_STATE_RESET = 'EMAIL_VERIFY_STATE_RESET';
// export const EXPORT_ADVANCED_SETTINGS_FETCH = 'EXPORT_ADVANCED_SETTINGS_FETCH';
// export const EXPORT_ADVANCED_SETTINGS_FETCH_FAIL = 'EXPORT_ADVANCED_SETTINGS_FETCH_FAIL';
// export const EXPORT_ADVANCED_SETTINGS_RECEIVE = 'EXPORT_ADVANCED_SETTINGS_RECEIVE';
// export const EXPORT_CLEAR = 'EXPORT_CLEAR';
// export const EXPORT_COMPLETE = 'EXPORT_COMPLETE';
// export const EXPORT_FAILURE = 'EXPORT_FAILURE';
// export const EXPORT_POST_TYPE_FIELD_SET = 'EXPORT_POST_TYPE_FIELD_SET';
// export const EXPORT_POST_TYPE_SET = 'EXPORT_POST_TYPE_SET';
// export const EXPORT_STARTED = 'EXPORT_STARTED';
// export const EXPORT_START_REQUEST = 'EXPORT_START_REQUEST';
// export const EXPORT_STATUS_FETCH = 'EXPORT_STATUS_FETCH';
// export const FETCH_WPORG_PLUGIN_DATA = 'FETCH_WPORG_PLUGIN_DATA';
// export const FIRST_VIEW_HIDE = 'FIRST_VIEW_HIDE';
// export const FOLLOWERS_RECEIVE = 'FOLLOWERS_RECEIVE';
// export const FOLLOWERS_REQUEST = 'FOLLOWERS_REQUEST';
// export const FOLLOWERS_REQUEST_ERROR = 'FOLLOWERS_REQUEST_ERROR';
// export const FOLLOWER_REMOVE_ERROR = 'FOLLOWER_REMOVE_ERROR';
// export const FOLLOWER_REMOVE_REQUEST = 'FOLLOWER_REMOVE_REQUEST';
// export const FOLLOWER_REMOVE_SUCCESS = 'FOLLOWER_REMOVE_SUCCESS';
// export const GEO_RECEIVE = 'GEO_RECEIVE';
// export const GEO_REQUEST = 'GEO_REQUEST';
// export const GEO_REQUEST_FAILURE = 'GEO_REQUEST_FAILURE';
// export const GEO_REQUEST_SUCCESS = 'GEO_REQUEST_SUCCESS';
// export const GOOGLE_APPS_USERS_FETCH = 'GOOGLE_APPS_USERS_FETCH';
// export const GOOGLE_APPS_USERS_FETCH_COMPLETED = 'GOOGLE_APPS_USERS_FETCH_COMPLETED';
// export const GOOGLE_APPS_USERS_FETCH_FAILED = 'GOOGLE_APPS_USERS_FETCH_FAILED';
// export const GRAVATAR_RECEIVE_IMAGE_FAILURE = 'GRAVATAR_RECEIVE_IMAGE_FAILURE';
// export const GRAVATAR_UPLOAD_RECEIVE = 'GRAVATAR_UPLOAD_RECEIVE';
// export const GRAVATAR_UPLOAD_REQUEST = 'GRAVATAR_UPLOAD_REQUEST';
// export const GRAVATAR_UPLOAD_REQUEST_FAILURE = 'GRAVATAR_UPLOAD_REQUEST_FAILURE';
// export const GRAVATAR_UPLOAD_REQUEST_SUCCESS = 'GRAVATAR_UPLOAD_REQUEST_SUCCESS';
// export const GUIDED_TOUR_UPDATE = 'GUIDED_TOUR_UPDATE';
// export const GUIDED_TRANSFER_HOST_DETAILS_SAVE = 'GUIDED_TRANSFER_HOST_DETAILS_SAVE';
// export const GUIDED_TRANSFER_HOST_DETAILS_SAVE_FAILURE =
// 	'GUIDED_TRANSFER_HOST_DETAILS_SAVE_FAILURE';
// export const GUIDED_TRANSFER_HOST_DETAILS_SAVE_SUCCESS =
// 	'GUIDED_TRANSFER_HOST_DETAILS_SAVE_SUCCESS';
// export const GUIDED_TRANSFER_STATUS_RECEIVE = 'GUIDED_TRANSFER_STATUS_RECEIVE';
// export const GUIDED_TRANSFER_STATUS_REQUEST = 'GUIDED_TRANSFER_STATUS_REQUEST';
// export const GUIDED_TRANSFER_STATUS_REQUEST_FAILURE = 'GUIDED_TRANSFER_STATUS_REQUEST_FAILURE';
// export const GUIDED_TRANSFER_STATUS_REQUEST_SUCCESS = 'GUIDED_TRANSFER_STATUS_REQUEST_SUCCESS';
// export const HAPPINESS_ENGINEERS_FETCH = 'HAPPINESS_ENGINEERS_FETCH';
// export const HAPPINESS_ENGINEERS_FETCH_FAILURE = 'HAPPINESS_ENGINEERS_FETCH_FAILURE';
// export const HAPPINESS_ENGINEERS_FETCH_SUCCESS = 'HAPPINESS_ENGINEERS_FETCH_SUCCESS';
// export const HAPPINESS_ENGINEERS_RECEIVE = 'HAPPINESS_ENGINEERS_RECEIVE';
// export const HAPPYCHAT_BLUR = 'HAPPYCHAT_BLUR';
// export const HAPPYCHAT_FOCUS = 'HAPPYCHAT_FOCUS';
// export const HAPPYCHAT_ELIGIBILITY_SET = 'HAPPYCHAT_ELIGIBILITY_SET';
// export const HAPPYCHAT_IO_INIT = 'HAPPYCHAT_IO_INIT';
// export const HAPPYCHAT_IO_RECEIVE_ACCEPT = 'HAPPYCHAT_IO_RECEIVE_ACCEPT';
// export const HAPPYCHAT_IO_RECEIVE_CONNECT = 'HAPPYCHAT_IO_RECEIVE_CONNECT';
// export const HAPPYCHAT_IO_RECEIVE_DISCONNECT = 'HAPPYCHAT_IO_RECEIVE_DISCONNECT';
// export const HAPPYCHAT_IO_RECEIVE_ERROR = 'HAPPYCHAT_IO_RECEIVE_ERROR';
// export const HAPPYCHAT_IO_RECEIVE_INIT = 'HAPPYCHAT_IO_RECEIVE_INIT';
// export const HAPPYCHAT_IO_RECEIVE_LOCALIZED_SUPPORT = 'HAPPYCHAT_IO_RECEIVE_LOCALIZED_SUPPORT';
// export const HAPPYCHAT_IO_RECEIVE_MESSAGE = 'HAPPYCHAT_IO_RECEIVE_MESSAGE';
// export const HAPPYCHAT_IO_RECEIVE_RECONNECTING = 'HAPPYCHAT_IO_RECEIVE_RECONNECTING';
// export const HAPPYCHAT_IO_RECEIVE_STATUS = 'HAPPYCHAT_IO_RECEIVE_STATUS';
// export const HAPPYCHAT_IO_RECEIVE_TOKEN = 'HAPPYCHAT_IO_RECEIVE_TOKEN';
// export const HAPPYCHAT_IO_RECEIVE_UNAUTHORIZED = 'HAPPYCHAT_IO_RECEIVE_UNAUTHORIZED';
// export const HAPPYCHAT_IO_REQUEST_TRANSCRIPT = 'HAPPYCHAT_IO_REQUEST_TRANSCRIPT';
// export const HAPPYCHAT_IO_REQUEST_TRANSCRIPT_RECEIVE = 'HAPPYCHAT_IO_REQUEST_TRANSCRIPT_RECEIVE';
// export const HAPPYCHAT_IO_REQUEST_TRANSCRIPT_TIMEOUT = 'HAPPYCHAT_IO_REQUEST_TRANSCRIPT_TIMEOUT';
// export const HAPPYCHAT_IO_SEND_MESSAGE_EVENT = 'HAPPYCHAT_IO_SEND_MESSAGE_EVENT';
// export const HAPPYCHAT_IO_SEND_MESSAGE_LOG = 'HAPPYCHAT_IO_SEND_MESSAGE_LOG';
// export const HAPPYCHAT_IO_SEND_MESSAGE_MESSAGE = 'HAPPYCHAT_IO_SEND_MESSAGE_MESSAGE';
// export const HAPPYCHAT_IO_SEND_MESSAGE_USERINFO = 'HAPPYCHAT_IO_SEND_MESSAGE_USERINFO';
// export const HAPPYCHAT_IO_SEND_PREFERENCES = 'HAPPYCHAT_IO_SEND_PREFERENCES';
// export const HAPPYCHAT_IO_SEND_TYPING = 'HAPPYCHAT_IO_SEND_TYPING';
// export const HAPPYCHAT_MINIMIZING = 'HAPPYCHAT_MINIMIZING';
// export const HAPPYCHAT_OPEN = 'HAPPYCHAT_OPEN';
// export const HAPPYCHAT_SET_CURRENT_MESSAGE = 'HAPPYCHAT_SET_CURRENT_MESSAGE';
// export const HELP_COURSES_RECEIVE = 'HELP_COURSES_RECEIVE';
// export const HELP_CONTACT_FORM_SITE_SELECT = 'HELP_CONTACT_FORM_SITE_SELECT';
// export const HELP_TICKET_CONFIGURATION_DISMISS_ERROR = 'HELP_TICKET_CONFIGURATION_DISMISS_ERROR';
// export const HELP_TICKET_CONFIGURATION_REQUEST = 'HELP_TICKET_CONFIGURATION_REQUEST';
// export const HELP_TICKET_CONFIGURATION_REQUEST_FAILURE =
// 	'HELP_TICKET_CONFIGURATION_REQUEST_FAILURE';
// export const HELP_TICKET_CONFIGURATION_REQUEST_SUCCESS =
// 	'HELP_TICKET_CONFIGURATION_REQUEST_SUCCESS';
// export const HTTP_REQUEST = 'HTTP_REQUEST';
// export const I18N_LANGUAGE_NAMES_REQUEST = 'I18N_LANGUAGE_NAMES_REQUEST';
// export const I18N_LANGUAGE_NAMES_ADD = 'I18N_LANGUAGE_NAMES_ADD';
// export const I18N_LOCALE_SUGGESTIONS_REQUEST = 'I18N_LOCALE_SUGGESTIONS_REQUEST';
// export const I18N_LOCALE_SUGGESTIONS_ADD = 'I18N_LOCALE_SUGGESTIONS_ADD';
// export const IMAGE_EDITOR_COMPUTED_CROP = 'IMAGE_EDITOR_COMPUTED_CROP';
// export const IMAGE_EDITOR_CROP = 'IMAGE_EDITOR_CROP';
// export const IMAGE_EDITOR_FLIP = 'IMAGE_EDITOR_FLIP';
// export const IMAGE_EDITOR_IMAGE_HAS_LOADED = 'IMAGE_EDITOR_IMAGE_HAS_LOADED';
// export const IMAGE_EDITOR_ROTATE_COUNTERCLOCKWISE = 'IMAGE_EDITOR_ROTATE_COUNTERCLOCKWISE';
// export const IMAGE_EDITOR_SET_ASPECT_RATIO = 'IMAGE_EDITOR_SET_ASPECT_RATIO';
// export const IMAGE_EDITOR_SET_CROP_BOUNDS = 'IMAGE_EDITOR_SET_CROP_BOUNDS';
// export const IMAGE_EDITOR_SET_DEFAULT_ASPECT_RATIO = 'IMAGE_EDITOR_SET_DEFAULT_ASPECT_RATIO';
// export const IMAGE_EDITOR_SET_FILE_INFO = 'IMAGE_EDITOR_SET_FILE_INFO';
// export const IMAGE_EDITOR_STATE_RESET = 'IMAGE_EDITOR_STATE_RESET';
// export const IMAGE_EDITOR_STATE_RESET_ALL = 'IMAGE_EDITOR_STATE_RESET_ALL';
// export const IMPORTS_AUTHORS_SET_MAPPING = 'IMPORTS_AUTHORS_SET_MAPPING';
// export const IMPORTS_AUTHORS_START_MAPPING = 'IMPORTS_AUTHORS_START_MAPPING';
// export const IMPORTS_FETCH = 'IMPORTS_FETCH';
// export const IMPORTS_FETCH_COMPLETED = 'IMPORTS_FETCH_COMPLETED';
// export const IMPORTS_FETCH_FAILED = 'IMPORTS_FETCH_FAILED';
// export const IMPORTS_IMPORT_CANCEL = 'IMPORTS_IMPORT_CANCEL';
// export const IMPORTS_IMPORT_LOCK = 'IMPORTS_IMPORT_LOCK';
// export const IMPORTS_IMPORT_RECEIVE = 'IMPORTS_IMPORT_RECEIVE';
// export const IMPORTS_IMPORT_RESET = 'IMPORTS_IMPORT_RESET';
// export const IMPORTS_IMPORT_START = 'IMPORTS_IMPORT_START';
// export const IMPORTS_IMPORT_UNLOCK = 'IMPORTS_IMPORT_UNLOCK';
// export const IMPORTS_START_IMPORTING = 'IMPORTS_START_IMPORTING';
// export const IMPORTS_STORE_RESET = 'IMPORTS_STORE_RESET';
// export const IMPORTS_UPLOAD_COMPLETED = 'IMPORTS_UPLOAD_COMPLETED';
// export const IMPORTS_UPLOAD_FAILED = 'IMPORTS_UPDLOAD_FAILED';
// export const IMPORTS_UPLOAD_SET_PROGRESS = 'IMPORTS_UPLOAD_SET_PROGRESS';
// export const IMPORTS_UPLOAD_START = 'IMPORTS_UPLOAD_START';
// export const INLINE_HELP_SEARCH_REQUEST = 'INLINE_HELP_SEARCH_REQUEST';
// export const INLINE_HELP_SEARCH_REQUEST_FAILURE = 'INLINE_HELP_SEARCH_REQUEST_FAILURE';
// export const INLINE_HELP_SEARCH_REQUEST_SUCCESS = 'INLINE_HELP_SEARCH_REQUEST_SUCCESS';
// export const INLINE_HELP_SELECT_NEXT_RESULT = 'INLINE_HELP_SELECT_NEXT_RESULT';
// export const INLINE_HELP_SELECT_PREVIOUS_RESULT = 'INLINE_HELP_SELECT_PREVIOUS_RESULT';
// export const INVITES_DELETE_REQUEST = 'INVITES_DELETE_REQUEST';
// export const INVITES_DELETE_REQUEST_FAILURE = 'INVITES_DELETE_REQUEST_FAILURE';
// export const INVITES_DELETE_REQUEST_SUCCESS = 'INVITES_DELETE_REQUEST_SUCCESS';
// export const INVITES_REQUEST = 'INVITES_REQUEST';
// export const INVITES_REQUEST_FAILURE = 'INVITES_REQUEST_FAILURE';
// export const INVITES_REQUEST_SUCCESS = 'INVITES_REQUEST_SUCCESS';
// export const INVITE_RESEND_REQUEST = 'INVITE_RESEND_REQUEST';
// export const INVITE_RESEND_REQUEST_FAILURE = 'INVITE_RESEND_REQUEST_FAILURE';
// export const INVITE_RESEND_REQUEST_SUCCESS = 'INVITE_RESEND_REQUEST_SUCCESS';
// export const LAYOUT_FOCUS_SET = 'LAYOUT_FOCUS_SET';
// export const LAYOUT_NEXT_FOCUS_ACTIVATE = 'LAYOUT_NEXT_FOCUS_ACTIVATE';
// export const LAYOUT_NEXT_FOCUS_SET = 'LAYOUT_NEXT_FOCUS_SET';
// export const LOCALE_SET = 'LOCALE_SET';
// export const LOGIN_AUTH_ACCOUNT_TYPE_REQUEST = 'LOGIN_AUTH_ACCOUNT_TYPE_REQUEST';
// export const LOGIN_AUTH_ACCOUNT_TYPE_REQUESTING = 'LOGIN_AUTH_ACCOUNT_TYPE_REQUESTING';
// export const LOGIN_AUTH_ACCOUNT_TYPE_REQUEST_FAILURE = 'LOGIN_AUTH_ACCOUNT_TYPE_REQUEST_FAILURE';
// export const LOGIN_AUTH_ACCOUNT_TYPE_REQUEST_SUCCESS = 'LOGIN_AUTH_ACCOUNT_TYPE_REQUEST_SUCCESS';
// export const LOGIN_AUTH_ACCOUNT_TYPE_RESET = 'LOGIN_AUTH_ACCOUNT_TYPE_RESET';
// export const LOGIN_FORM_UPDATE = 'LOGIN_FORM_UPDATE';
// export const LOGIN_REQUEST = 'LOGIN_REQUEST';
// export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';
// export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
// export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
// export const LOGOUT_REQUEST_FAILURE = 'LOGOUT_REQUEST_FAILURE';
// export const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS';
// export const LOGSTASH = 'LOGSTASH';
// export const OAUTH2_CLIENT_DATA_REQUEST = 'OAUTH2_CLIENT_DATA_REQUEST';
// export const OAUTH2_CLIENT_DATA_REQUEST_FAILURE = 'OAUTH2_CLIENT_DATA_REQUEST_FAILURE';
// export const OAUTH2_CLIENT_DATA_REQUEST_SUCCESS = 'OAUTH2_CLIENT_DATA_REQUEST_SUCCESS';
// export const POSTS_RECEIVE = 'POSTS_RECEIVE';
// export const POSTS_REQUEST = 'POSTS_REQUEST';
// export const POSTS_REQUEST_FAILURE = 'POSTS_REQUEST_FAILURE';
// export const POSTS_REQUEST_SUCCESS = 'POSTS_REQUEST_SUCCESS';
// export const POST_COUNTS_RECEIVE = 'POST_COUNTS_RECEIVE';
// export const POST_COUNTS_REQUEST = 'POST_COUNTS_REQUEST';
// export const POST_COUNTS_REQUEST_FAILURE = 'POST_COUNTS_REQUEST_FAILURE';
// export const POST_COUNTS_REQUEST_SUCCESS = 'POST_COUNTS_REQUEST_SUCCESS';
// export const POST_COUNTS_RESET_INTERNAL_STATE = 'POST_COUNTS_RESET_INTERNAL_STATE';
// export const POST_DELETE = 'POST_DELETE';
// export const POST_DELETE_FAILURE = 'POST_DELETE_FAILURE';
// export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
// export const POST_EDIT = 'POST_EDIT';
// export const POST_FORMATS_RECEIVE = 'POST_FORMATS_RECEIVE';
// export const POST_FORMATS_REQUEST = 'POST_FORMATS_REQUEST';
// export const POST_FORMATS_REQUEST_FAILURE = 'POST_FORMATS_REQUEST_FAILURE';
// export const POST_FORMATS_REQUEST_SUCCESS = 'POST_FORMATS_REQUEST_SUCCESS';
// export const POST_LIKE = 'POST_LIKE';
// export const POST_LIKES_ADD_LIKER = 'POST_LIKES_ADD_LIKER';
// export const POST_LIKES_RECEIVE = 'POST_LIKES_RECEIVE';
// export const POST_LIKES_REMOVE_LIKER = 'POST_LIKES_REMOVE_LIKER';
// export const POST_LIKES_REQUEST = 'POST_LIKES_REQUEST';
// export const POST_REQUEST = 'POST_REQUEST';
// export const POST_REQUEST_FAILURE = 'POST_REQUEST_FAILURE';
// export const POST_REQUEST_SUCCESS = 'POST_REQUEST_SUCCESS';
// export const POST_RESTORE = 'POST_RESTORE';
// export const POST_RESTORE_FAILURE = 'POST_RESTORE_FAILURE';
// export const POST_RESTORE_SUCCESS = 'POST_RESTORE_SUCCESS';
// export const POST_REVISIONS_DIALOG_CLOSE = 'POST_REVISIONS_DIALOG_CLOSE';
// export const POST_REVISIONS_DIALOG_OPEN = 'POST_REVISIONS_DIALOG_OPEN';
// export const POST_REVISIONS_RECEIVE = 'POST_REVISIONS_RECEIVE';
// export const POST_REVISIONS_REQUEST = 'POST_REVISIONS_REQUEST';
// export const POST_REVISIONS_REQUEST_FAILURE = 'POST_REVISIONS_REQUEST_FAILURE';
// export const POST_REVISIONS_REQUEST_SUCCESS = 'POST_REVISIONS_REQUEST_SUCCESS';
// export const POST_REVISIONS_SELECT = 'POST_REVISIONS_SELECT';
// export const POST_SAVE = 'POST_SAVE';
// export const POST_SAVE_FAILURE = 'POST_SAVE_FAILURE';
// export const POST_SAVE_SUCCESS = 'POST_SAVE_SUCCESS';
// export const POST_STATS_RECEIVE = 'POST_STATS_RECEIVE';
// export const POST_STATS_REQUEST = 'POST_STATS_REQUEST';
// export const POST_STATS_REQUEST_FAILURE = 'POST_STATS_REQUEST_FAILURE';
// export const POST_STATS_REQUEST_SUCCESS = 'POST_STATS_REQUEST_SUCCESS';
// export const POST_TYPE_LIST_LIKES_POPOVER_HIDE = 'POST_TYPE_LIST_LIKES_POPOVER_HIDE';
// export const POST_TYPE_LIST_LIKES_POPOVER_TOGGLE = 'POST_TYPE_LIST_LIKES_POPOVER_TOGGLE';
// export const POST_TYPE_LIST_MULTI_SELECTION_MODE_TOGGLE =
// 	'POST_TYPE_LIST_MULTI_SELECTION_MODE_TOGGLE';
// 	export const POST_TYPE_LIST_MULTI_SELECTION_MODE_ACTIVE =
// 	'POST_TYPE_LIST_MULTI_SELECTION_MODE_ACTIVE';
// export const POST_TYPE_LIST_SELECTION_TOGGLE = 'POST_TYPE_LIST_SELECTION_TOGGLE';
// export const POST_TYPE_LIST_SHARE_PANEL_HIDE = 'POST_TYPE_LIST_SHARE_PANEL_HIDE';
// export const POST_TYPE_LIST_SHARE_PANEL_TOGGLE = 'POST_TYPE_LIST_SHARE_PANEL_TOGGLE';
// export const POST_TYPES_RECEIVE = 'POST_TYPES_RECEIVE';
// export const POST_TYPES_REQUEST = 'POST_TYPES_REQUEST';
// export const POST_TYPES_TAXONOMIES_RECEIVE = 'POST_TYPES_TAXONOMIES_RECEIVE';
// export const POST_TYPES_TAXONOMIES_REQUEST = 'POST_TYPES_TAXONOMIES_REQUEST';
// export const POST_TYPES_TAXONOMIES_REQUEST_FAILURE = 'POST_TYPES_TAXONOMIES_REQUEST_FAILURE';
// export const POST_TYPES_TAXONOMIES_REQUEST_SUCCESS = 'POST_TYPES_TAXONOMIES_REQUEST_SUCCESS';
// export const MAGIC_LOGIN_HIDE_REQUEST_FORM = 'MAGIC_LOGIN_HIDE_REQUEST_FORM';
// export const MAGIC_LOGIN_HIDE_REQUEST_NOTICE = 'MAGIC_LOGIN_HIDE_REQUEST_NOTICE';
// export const MAGIC_LOGIN_REQUEST_AUTH_ERROR = 'MAGIC_LOGIN_REQUEST_AUTH_ERROR';
// export const MAGIC_LOGIN_REQUEST_AUTH_FETCH = 'MAGIC_LOGIN_REQUEST_AUTH_FETCH';
// export const MAGIC_LOGIN_REQUEST_AUTH_SUCCESS = 'MAGIC_LOGIN_REQUEST_AUTH_SUCCESS';
// export const MAGIC_LOGIN_REQUEST_LOGIN_EMAIL_ERROR = 'MAGIC_LOGIN_REQUEST_LOGIN_EMAIL_ERROR';
// export const MAGIC_LOGIN_REQUEST_LOGIN_EMAIL_FETCH = 'MAGIC_LOGIN_REQUEST_LOGIN_EMAIL_FETCH';
// export const MAGIC_LOGIN_REQUEST_LOGIN_EMAIL_SUCCESS = 'MAGIC_LOGIN_REQUEST_LOGIN_EMAIL_SUCCESS';
// export const MAGIC_LOGIN_RESET_REQUEST_FORM = 'MAGIC_LOGIN_RESET_REQUEST_FORM';
// export const MAGIC_LOGIN_SHOW_CHECK_YOUR_EMAIL_PAGE = 'MAGIC_LOGIN_SHOW_CHECK_YOUR_EMAIL_PAGE';
// export const MAGIC_LOGIN_SHOW_INTERSTITIAL_PAGE = 'MAGIC_LOGIN_SHOW_INTERSTITIAL_PAGE';
// export const MAGIC_LOGIN_SHOW_LINK_EXPIRED = 'MAGIC_LOGIN_SHOW_LINK_EXPIRED';
// export const MASTERBAR_TOGGLE_VISIBILITY = 'MASTERBAR_TOGGLE_VISIBILITY';
// export const MEDIA_DELETE = 'MEDIA_DELETE';
// export const MEDIA_ITEM_REQUEST = 'MEDIA_ITEM_REQUEST';
// export const MEDIA_ITEM_REQUESTING = 'MEDIA_ITEM_REQUESTING';
// export const MEDIA_ITEM_REQUEST_FAILURE = 'MEDIA_ITEM_REQUEST_FAILURE';
// export const MEDIA_ITEM_REQUEST_SUCCESS = 'MEDIA_ITEM_REQUEST_SUCCESS';
// export const MEDIA_MODAL_VIEW_SET = 'MEDIA_MODAL_VIEW_SET';
// export const MEDIA_RECEIVE = 'MEDIA_RECEIVE';
// export const MEDIA_REQUEST = 'MEDIA_REQUEST';
// export const MEDIA_REQUESTING = 'MEDIA_REQUESTING';
// export const MEDIA_REQUEST_FAILURE = 'MEDIA_REQUEST_FAILURE';
// export const MEDIA_REQUEST_SUCCESS = 'MEDIA_REQUEST_SUCCESS';
export const FETCHING_MEDIA_ITEMS = 'FETCHING_MEDIA_ITEMS';

export const NAVIGATE = 'NAVIGATE';
export const NOTICE_CREATE = 'NOTICE_CREATE';
export const NOTICE_REMOVE = 'NOTICE_REMOVE';
// export const NOTIFICATION_SETTINGS_UPDATE = 'NOTIFICATION_SETTINGS_UPDATE';
// export const NOTIFICATION_SETTINGS_REQUEST = 'NOTIFICATION_SETTINGS_REQUEST';
// export const NOTIFICATIONS_PANEL_TOGGLE = 'NOTIFICATIONS_PANEL_TOGGLE';
// export const NPS_SURVEY_DIALOG_IS_SHOWING = 'NPS_SURVEY_DIALOG_IS_SHOWING';
// export const NPS_SURVEY_MARK_SHOWN_THIS_SESSION = 'NPS_SURVEY_MARK_SHOWN_THIS_SESSION';
// export const NPS_SURVEY_SET_ELIGIBILITY = 'NPS_SURVEY_SET_ELIGIBILITY';
// export const NPS_SURVEY_SUBMIT_REQUESTING = 'NPS_SURVEY_SUBMIT_REQUESTING';
// export const NPS_SURVEY_SUBMIT_REQUEST_FAILURE = 'NPS_SURVEY_SUBMIT_FAILURE';
// export const NPS_SURVEY_SUBMIT_REQUEST_SUCCESS = 'NPS_SURVEY_SUBMIT_SUCCESS';
// export const NPS_SURVEY_SUBMIT_WITH_NO_SCORE_REQUESTING =
// 	'NPS_SURVEY_SUBMIT_WITH_NO_SCORE_REQUESTING';
// export const NPS_SURVEY_SUBMIT_WITH_NO_SCORE_REQUEST_FAILURE =
// 	'NPS_SURVEY_SUBMIT_WITH_NO_SCORE_FAILURE';
// export const NPS_SURVEY_SUBMIT_WITH_NO_SCORE_REQUEST_SUCCESS =
// 	'NPS_SURVEY_SUBMIT_WITH_NO_SCORE_SUCCESS';

export const ROUTE_SET = 'ROUTE_SET';
export const SECTION_SET = 'SECTION_SET';
export const SELECTED_SITE_SET = 'SELECTED_SITE_SET';
// export const SELECTED_SITE_SUBSCRIBE = 'SELECTED_SITE_SUBSCRIBE';
// export const SELECTED_SITE_UNSUBSCRIBE = 'SELECTED_SITE_UNSUBSCRIBE';
// export const SEO_TITLE_SET = 'SEO_TITLE_SET';
export const SERIALIZE = 'SERIALIZE';
// export const SHARING_BUTTONS_RECEIVE = 'SHARING_BUTTONS_RECEIVE';
// export const SHARING_BUTTONS_REQUEST = 'SHARING_BUTTONS_REQUEST';
// export const SHARING_BUTTONS_REQUEST_FAILURE = 'SHARING_BUTTONS_REQUEST_FAILURE';
// export const SHARING_BUTTONS_REQUEST_SUCCESS = 'SHARING_BUTTONS_REQUEST_SUCCESS';
// export const SHARING_BUTTONS_SAVE = 'SHARING_BUTTONS_SAVE';
// export const SHARING_BUTTONS_SAVE_FAILURE = 'SHARING_BUTTONS_SAVE_FAILURE';
// export const SHARING_BUTTONS_SAVE_SUCCESS = 'SHARING_BUTTONS_SAVE_SUCCESS';
// export const SHARING_BUTTONS_UPDATE = 'SHARING_BUTTONS_UPDATE';
// export const SHORTCODE_RECEIVE = 'SHORTCODE_RECEIVE';
// export const SHORTCODE_REQUEST = 'SHORTCODE_REQUEST';
// export const SHORTCODE_REQUEST_FAILURE = 'SHORTCODE_REQUEST_FAILURE';
// export const SHORTCODE_REQUEST_SUCCESS = 'SHORTCODE_REQUEST_SUCCESS';
// export const SIGNUP_COMPLETE_RESET = 'SIGNUP_COMPLETE_RESET';
// export const SIGNUP_DEPENDENCY_STORE_UPDATE = 'SIGNUP_DEPENDENCY_STORE_UPDATE';
// export const SIGNUP_OPTIONAL_DEPENDENCY_SUGGESTED_USERNAME_SET =
// 	'SIGNUP_OPTIONAL_DEPENDENCY_SUGGESTED_USERNAME_SET';
// export const SIGNUP_STEPS_DESIGN_TYPE_SET = 'SIGNUP_STEPS_DESIGN_TYPE_SET';
// export const SIGNUP_STEPS_DOMAIN_SEARCH_PREFILL_SET = 'SIGNUP_STEPS_DOMAIN_SEARCH_PREFILL_SET';
// export const SIGNUP_STEPS_SITE_GOALS_SET = 'SIGNUP_STEPS_SITE_GOALS_SET';
// export const SIGNUP_STEPS_SITE_GOALS_ARRAY_SET = 'SIGNUP_STEPS_SITE_GOALS_ARRAY_SET';
// export const SIGNUP_STEPS_USER_EXPERIENCE_SET = 'SIGNUP_STEPS_USER_EXPERIENCE_SET';
// export const SIGNUP_STEPS_SITE_TITLE_SET = 'SIGNUP_STEPS_SITE_TITLE_SET';
// export const SIGNUP_STEPS_SURVEY_SET = 'SIGNUP_STEPS_SURVEY_SET';
// export const SIMPLE_PAYMENTS_PRODUCT_GET = 'SIMPLE_PAYMENTS_PRODUCT_GET';
// export const SIMPLE_PAYMENTS_PRODUCT_RECEIVE = 'SIMPLE_PAYMENTS_PRODUCT_RECEIVE';
// export const SIMPLE_PAYMENTS_PRODUCTS_LIST = 'SIMPLE_PAYMENTS_PRODUCTS_LIST';
// export const SIMPLE_PAYMENTS_PRODUCTS_LIST_ADD = 'SIMPLE_PAYMENTS_PRODUCTS_LIST_ADD';
// export const SIMPLE_PAYMENTS_PRODUCTS_LIST_EDIT = 'SIMPLE_PAYMENTS_PRODUCTS_LIST_EDIT';
// export const SIMPLE_PAYMENTS_PRODUCTS_LIST_DELETE = 'SIMPLE_PAYMENTS_PRODUCTS_LIST_DELETE';
// export const SIMPLE_PAYMENTS_PRODUCTS_LIST_RECEIVE = 'SIMPLE_PAYMENTS_PRODUCTS_LIST_RECEIVE';
// export const SIMPLE_PAYMENTS_PRODUCTS_LIST_RECEIVE_UPDATE =
// 	'SIMPLE_PAYMENTS_PRODUCTS_LIST_RECEIVE_UPDATE';
// export const SIMPLE_PAYMENTS_PRODUCTS_LIST_RECEIVE_DELETE =
// 	'SIMPLE_PAYMENTS_PRODUCTS_LIST_RECEIVE_DELETE';
// export const SITES_BLOG_STICKER_ADD = 'SITES_BLOG_STICKER_ADD';
// export const SITES_BLOG_STICKER_LIST = 'SITES_BLOG_STICKER_LIST';
// export const SITES_BLOG_STICKER_LIST_RECEIVE = 'SITES_BLOG_STICKER_LIST_RECEIVE';
// export const SITES_BLOG_STICKER_REMOVE = 'SITES_BLOG_STICKER_REMOVE';
// export const SITES_ONCE_CHANGED = 'SITES_ONCE_CHANGED';
// export const SITES_RECEIVE = 'SITES_RECEIVE';
// export const SITES_REQUEST = 'SITES_REQUEST';
// export const SITES_REQUEST_FAILURE = 'SITES_REQUEST_FAILURE';
// export const SITES_REQUEST_SUCCESS = 'SITES_REQUEST_SUCCESS';
// export const SITE_CHECKLIST_RECEIVE = 'SITE_CHECKLIST_RECEIVE';
// export const SITE_CHECKLIST_REQUEST = 'SITE_CHECKLIST_REQUEST';
// export const SITE_CHECKLIST_TASK_UPDATE = 'SITE_CHECKLIST_TASK_UPDATE';
// export const SITE_CONNECTION_STATUS_RECEIVE = 'SITE_CONNECTION_STATUS_RECEIVE';
// export const SITE_CONNECTION_STATUS_REQUEST = 'SITE_CONNECTION_STATUS_REQUEST';
// export const SITE_CONNECTION_STATUS_REQUEST_FAILURE = 'SITE_CONNECTION_STATUS_REQUEST_FAILURE';
// export const SITE_CONNECTION_STATUS_REQUEST_SUCCESS = 'SITE_CONNECTION_STATUS_REQUEST_SUCCESS';
// export const SITE_DELETE = 'SITE_DELETE';
// export const SITE_DELETE_FAILURE = 'SITE_DELETE_FAILURE';
// export const SITE_DELETE_RECEIVE = 'SITE_DELETE_RECEIVE';
// export const SITE_DELETE_SUCCESS = 'SITE_DELETE_SUCCESS';
// export const SITE_PLANS_FETCH = 'SITE_PLANS_FETCH';
// export const SITE_PLANS_FETCH_COMPLETED = 'SITE_PLANS_FETCH_COMPLETED';
// export const SITE_PLANS_FETCH_FAILED = 'SITE_PLANS_FETCH_FAILED';
// export const SITE_PLANS_REMOVE = 'SITE_PLANS_REMOVE';
// export const SITE_PLANS_TRIAL_CANCEL = 'SITE_PLANS_TRIAL_CANCEL';
// export const SITE_PLANS_TRIAL_CANCEL_COMPLETED = 'SITE_PLANS_TRIAL_CANCEL_COMPLETED';
// export const SITE_PLANS_TRIAL_CANCEL_FAILED = 'SITE_PLANS_TRIAL_CANCEL_FAILED';
// export const SITE_PLUGIN_UPDATED = 'SITE_PLUGIN_UPDATED';
// export const SITE_RENAME_REQUEST = 'SITE_RENAME_REQUEST';
// export const SITE_RENAME_REQUEST_FAILURE = 'SITE_RENAME_REQUEST_FAILURE';
// export const SITE_RENAME_REQUEST_SUCCESS = 'SITE_RENAME_REQUEST_SUCCESS';
// export const SITE_RECEIVE = 'SITE_RECEIVE';
// export const SITE_REQUEST = 'SITE_REQUEST';
// export const SITE_REQUEST_FAILURE = 'SITE_REQUEST_FAILURE';
// export const SITE_REQUEST_SUCCESS = 'SITE_REQUEST_SUCCESS';
// export const SITE_ROLES_RECEIVE = 'SITE_ROLES_RECEIVE';
// export const SITE_ROLES_REQUEST = 'SITE_ROLES_REQUEST';
// export const SITE_ROLES_REQUEST_FAILURE = 'SITE_ROLES_REQUEST_FAILURE';
// export const SITE_ROLES_REQUEST_SUCCESS = 'SITE_ROLES_REQUEST_SUCCESS';
// export const SITE_SETTINGS_RECEIVE = 'SITE_SETTINGS_RECEIVE';
// export const SITE_SETTINGS_REQUEST = 'SITE_SETTINGS_REQUEST';
// export const SITE_SETTINGS_REQUEST_FAILURE = 'SITE_SETTINGS_REQUEST_FAILURE';
// export const SITE_SETTINGS_REQUEST_SUCCESS = 'SITE_SETTINGS_REQUEST_SUCCESS';
// export const SITE_SETTINGS_SAVE = 'SITE_SETTINGS_SAVE';
// export const SITE_SETTINGS_SAVE_FAILURE = 'SITE_SETTINGS_SAVE_FAILURE';
// export const SITE_SETTINGS_SAVE_SUCCESS = 'SITE_SETTINGS_SAVE_SUCCESS';
// export const SITE_SETTINGS_UPDATE = 'SITE_SETTINGS_UPDATE';
// export const SITE_STATS_RECEIVE = 'SITE_STATS_RECEIVE';
// export const SITE_STATS_REQUEST = 'SITE_STATS_REQUEST';
// export const SITE_STATS_REQUEST_FAILURE = 'SITE_STATS_REQUEST_FAILURE';
// export const SITE_VOUCHERS_ASSIGN_RECEIVE = 'SITE_VOUCHERS_ASSIGN_RECEIVE';
// export const SITE_VOUCHERS_ASSIGN_REQUEST = 'SITE_VOUCHERS_ASSIGN_REQUEST';
// export const SITE_VOUCHERS_ASSIGN_REQUEST_FAILURE = 'SITE_VOUCHERS_ASSIGN_REQUEST_FAILURE';
// export const SITE_VOUCHERS_ASSIGN_REQUEST_SUCCESS = 'SITE_VOUCHERS_ASSIGN_REQUEST_SUCCESS';
// export const SITE_VOUCHERS_RECEIVE = 'SITE_VOUCHERS_RECEIVE';
// export const SITE_VOUCHERS_REQUEST = 'SITE_VOUCHERS_REQUEST';
// export const SITE_VOUCHERS_REQUEST_FAILURE = 'SITE_VOUCHERS_REQUEST_FAILURE';
// export const SITE_VOUCHERS_REQUEST_SUCCESS = 'SITE_VOUCHERS_REQUEST_SUCCESS';
// export const SOCIAL_LOGIN_REQUEST = 'SOCIAL_LOGIN_REQUEST';
// export const SOCIAL_LOGIN_REQUEST_SUCCESS = 'SOCIAL_LOGIN_REQUEST_SUCCESS';
// export const SOCIAL_LOGIN_REQUEST_FAILURE = 'SOCIAL_LOGIN_REQUEST_FAILURE';
// export const SOCIAL_CREATE_ACCOUNT_REQUEST = 'SOCIAL_CREATE_ACCOUNT_REQUEST';
// export const SOCIAL_CREATE_ACCOUNT_REQUEST_SUCCESS = 'SOCIAL_CREATE_ACCOUNT_REQUEST_SUCCESS';
// export const SOCIAL_CREATE_ACCOUNT_REQUEST_FAILURE = 'SOCIAL_CREATE_ACCOUNT_REQUEST_FAILURE';
// export const SOCIAL_CONNECT_ACCOUNT_REQUEST = 'SOCIAL_CONNECT_ACCOUNT_REQUEST';
// export const SOCIAL_CONNECT_ACCOUNT_REQUEST_SUCCESS = 'SOCIAL_CONNECT_ACCOUNT_REQUEST_SUCCESS';
// export const SOCIAL_CONNECT_ACCOUNT_REQUEST_FAILURE = 'SOCIAL_CONNECT_ACCOUNT_REQUEST_FAILURE';
// export const SOCIAL_DISCONNECT_ACCOUNT_REQUEST = 'SOCIAL_DISCONNECT_ACCOUNT_REQUEST';
// export const SOCIAL_DISCONNECT_ACCOUNT_REQUEST_SUCCESS =
// 	'SOCIAL_DISCONNECT_ACCOUNT_REQUEST_SUCCESS';
// export const SOCIAL_DISCONNECT_ACCOUNT_REQUEST_FAILURE =
// 	'SOCIAL_DISCONNECT_ACCOUNT_REQUEST_FAILURE';
// export const STORED_CARDS_ADD_COMPLETED = 'STORED_CARDS_ADD_COMPLETED';
// export const STORED_CARDS_DELETE = 'STORED_CARDS_DELETE';
// export const STORED_CARDS_DELETE_COMPLETED = 'STORED_CARDS_DELETE_COMPLETED';
// export const STORED_CARDS_DELETE_FAILED = 'STORED_CARDS_DELETE_FAILED';
// export const STORED_CARDS_FETCH = 'STORED_CARDS_FETCH';
// export const STORED_CARDS_FETCH_COMPLETED = 'STORED_CARDS_FETCH_COMPLETED';
// export const STORED_CARDS_FETCH_FAILED = 'STORED_CARDS_FETCH_FAILED';
// export const SUPPORT_USER_ACTIVATE = 'SUPPORT_USER_ACTIVATE';
// export const TERMS_RECEIVE = 'TERMS_RECEIVE';
// export const TERMS_REQUEST = 'TERMS_REQUEST';
// export const TERMS_REQUEST_FAILURE = 'TERMS_REQUEST_FAILURE';
// export const TERMS_REQUEST_SUCCESS = 'TERMS_REQUEST_SUCCESS';
// export const TERM_REMOVE = 'TERM_REMOVE';
// export const TIMEZONES_RECEIVE = 'TIMEZONES_RECEIVE';
// export const TIMEZONES_REQUEST = 'TIMEZONES_REQUEST';
// export const TWO_FACTOR_AUTHENTICATION_LOGIN_REQUEST = 'TWO_FACTOR_AUTHENTICATION_LOGIN_REQUEST';
// export const TWO_FACTOR_AUTHENTICATION_LOGIN_REQUEST_FAILURE =
// 	'TWO_FACTOR_AUTHENTICATION_LOGIN_REQUEST_FAILURE';
// export const TWO_FACTOR_AUTHENTICATION_LOGIN_REQUEST_SUCCESS =
// 	'TWO_FACTOR_AUTHENTICATION_LOGIN_REQUEST_SUCCESS';
// export const TWO_FACTOR_AUTHENTICATION_PUSH_POLL_COMPLETED =
// 	'TWO_FACTOR_AUTHENTICATION_PUSH_POLL_COMPLETED';
// export const TWO_FACTOR_AUTHENTICATION_PUSH_POLL_START =
// 	'TWO_FACTOR_AUTHENTICATION_PUSH_POLL_START';
// export const TWO_FACTOR_AUTHENTICATION_PUSH_POLL_STOP = 'TWO_FACTOR_AUTHENTICATION_PUSH_POLL_STOP';
// export const TWO_FACTOR_AUTHENTICATION_SEND_SMS_CODE_REQUEST =
// 	'TWO_FACTOR_AUTHENTICATION_SEND_SMS_CODE_REQUEST';
// export const TWO_FACTOR_AUTHENTICATION_SEND_SMS_CODE_REQUEST_FAILURE =
// 	'TWO_FACTOR_AUTHENTICATION_SEND_SMS_CODE_REQUEST_FAILURE';
// export const TWO_FACTOR_AUTHENTICATION_SEND_SMS_CODE_REQUEST_SUCCESS =
// 	'TWO_FACTOR_AUTHENTICATION_SEND_SMS_CODE_REQUEST_SUCCESS';
// export const TWO_FACTOR_AUTHENTICATION_UPDATE_NONCE = 'TWO_FACTOR_AUTHENTICATION_UPDATE_NONCE';
// export const USER_DEVICES_ADD = 'USER_DEVICES_ADD';
// export const USER_DEVICES_REQUEST = 'USER_DEVICES_REQUEST';
// export const USER_PROFILE_LINKS_ADD = 'USER_PROFILE_LINKS_ADD';
// export const USER_PROFILE_LINKS_ADD_DUPLICATE = 'USER_PROFILE_LINKS_ADD_DUPLICATE';
// export const USER_PROFILE_LINKS_ADD_FAILURE = 'USER_PROFILE_LINKS_ADD_FAILURE';
// export const USER_PROFILE_LINKS_ADD_MALFORMED = 'USER_PROFILE_LINKS_ADD_MALFORMED';
// export const USER_PROFILE_LINKS_ADD_SUCCESS = 'USER_PROFILE_LINKS_ADD_SUCCESS';
// export const USER_PROFILE_LINKS_DELETE = 'USER_PROFILE_LINKS_DELETE';
// export const USER_PROFILE_LINKS_DELETE_FAILURE = 'USER_PROFILE_LINKS_DELETE_FAILURE';
// export const USER_PROFILE_LINKS_DELETE_SUCCESS = 'USER_PROFILE_LINKS_DELETE_SUCCESS';
// export const USER_PROFILE_LINKS_RECEIVE = 'USER_PROFILE_LINKS_RECEIVE';
// export const USER_PROFILE_LINKS_REQUEST = 'USER_PROFILE_LINKS_REQUEST';
// export const USER_PROFILE_LINKS_RESET_ERRORS = 'USER_PROFILE_LINKS_RESET_ERRORS';
// export const USER_RECEIVE = 'USER_RECEIVE';
// export const USERS_REQUEST = 'USERS_REQUEST';
// export const USER_SETTINGS_REQUEST = 'USER_SETTINGS_REQUEST';
// export const USER_SETTINGS_SAVE = 'USER_SETTINGS_SAVE';
// export const USER_SETTINGS_UNSAVED_CLEAR = 'USER_SETTINGS_UNSAVED_CLEAR';
// export const USER_SETTINGS_UNSAVED_REMOVE = 'USER_SETTINGS_UNSAVED_REMOVE';
// export const USER_SETTINGS_UNSAVED_SET = 'USER_SETTINGS_UNSAVED_SET';
// export const USER_SETTINGS_UPDATE = 'USER_SETTINGS_UPDATE';
// export const USER_SUGGESTIONS_RECEIVE = 'USER_SUGGESTIONS_RECEIVE';
// export const USER_SUGGESTIONS_REQUEST = 'USER_SUGGESTIONS_REQUEST';
// export const USER_SUGGESTIONS_REQUEST_FAILURE = 'USER_SUGGESTIONS_REQUEST_FAILURE';
// export const USER_SUGGESTIONS_REQUEST_SUCCESS = 'USER_SUGGESTIONS_REQUEST_SUCCESS';
// export const VIDEO_EDITOR_SET_POSTER_URL = 'VIDEO_EDITOR_SET_POSTER_URL';
// export const VIDEO_EDITOR_SHOW_ERROR = 'VIDEO_EDITOR_SHOW_ERROR';
// export const VIDEO_EDITOR_SHOW_UPLOAD_PROGRESS = 'VIDEO_EDITOR_SHOW_UPLOAD_PROGRESS';
// export const VIDEO_EDITOR_UPDATE_POSTER = 'VIDEO_EDITOR_UPDATE_POSTER';
// export const WORDADS_SITE_APPROVE_REQUEST = 'WORDADS_SITE_APPROVE_REQUEST';
// export const WORDADS_SITE_APPROVE_REQUEST_DISMISS_ERROR =
// 	'WORDADS_SITE_APPROVE_REQUEST_DISMISS_ERROR';
// export const WORDADS_SITE_APPROVE_REQUEST_DISMISS_SUCCESS =
// 	'WORDADS_SITE_APPROVE_REQUEST_DISMISS_SUCCESS';
// export const WORDADS_SITE_APPROVE_REQUEST_FAILURE = 'WORDADS_SITE_APPROVE_REQUEST_FAILURE';
// export const WORDADS_SITE_APPROVE_REQUEST_SUCCESS = 'WORDADS_SITE_APPROVE_REQUEST_SUCCESS';
// export const WORDADS_STATUS_REQUEST = 'WORDADS_STATUS_REQUEST';
// export const WORDADS_STATUS_REQUEST_FAILURE = 'WORDADS_STATUS_REQUEST_FAILURE';
// export const WORDADS_STATUS_REQUEST_SUCCESS = 'WORDADS_STATUS_REQUEST_SUCCESS';
// export const WPCOM_HTTP_REQUEST = 'WPCOM_HTTP_REQUEST';
// export const WPORG_PLUGIN_DATA_RECEIVE = 'WPORG_PLUGIN_DATA_RECEIVE';

export const USER_RECEIVE = 'USER_RECEIVE';
export const USER_LOGOUT = 'USER_LOGOUT';

// export const SITE_CREATE_SUCCESS = 'SITE_CREATE_SUCCESS';
// export const SITE_CREATE_FAILURE = 'SITE_CREATE_FAILURE';

// export const SITE_ORDER_STATUSES_RECEIVE = 'SITE_ORDER_STATUSES_RECEIVE';
// export const SITE_ORDER_STATUSES_REQUEST = 'SITE_ORDER_STATUSES_REQUEST';
// export const SITE_ORDER_STATUSES_REQUEST_FAILURE = 'SITE_ORDER_STATUSES_REQUEST_FAILURE';
// export const SITE_ORDER_STATUSES_REQUEST_SUCCESS = 'SITE_ORDER_STATUSES_REQUEST_SUCCESS';
// export const SITE_ORDER_STATUSES_SAVE = 'SITE_ORDER_STATUSES_SAVE';
// export const SITE_ORDER_STATUSES_SAVE_FAILURE = 'SITE_ORDER_STATUSES_SAVE_FAILURE';
// export const SITE_ORDER_STATUSES_SAVE_SUCCESS = 'SITE_ORDER_STATUSES_SAVE_SUCCESS';
// export const SITE_ORDER_STATUSES_UPDATE = 'SITE_ORDER_STATUSES_UPDATE';

// export const CONVERSATION_TYPE_LIST_SELECTION_TOGGLE = 'CONVERSATION_TYPE_LIST_SELECTION_TOGGLE';
// export const CONVERSATION_TYPE_LIST_SELECTION_RESET = 'CONVERSATION_TYPE_LIST_SELECTION_RESET';
// export const CONVERSATION_TYPE_LIST_SHARE_PANEL_HIDE = 'CONVERSATION_TYPE_LIST_SHARE_PANEL_HIDE';
// export const CONVERSATION_TYPE_LIST_SHARE_PANEL_TOGGLE = 'CONVERSATION_TYPE_LIST_SHARE_PANEL_TOGGLE';

// export const ORDERS_REQUEST = 'ORDERS_REQUEST';
// export const ORDERS_RECEIVE = 'ORDERS_RECEIVE';
// export const ORDERS_REQUEST_SUCCESS = 'ORDERS_REQUEST_SUCCESS';
// export const ORDERS_REQUEST_FAILURE = 'ORDERS_REQUEST_FAILURE';
// export const ORDER_DELETE = 'CONVERSATION_DELETE';
// export const ORDER_DELETE_SUCCESS = 'CONVERSATION_DELETE_SUCCESS';
// export const ORDER_DELETE_FAILURE = 'CONVERSATION_DELETE_FAILURE';
// export const ORDER_EDIT = 'CONVERSATION_EDIT';
// export const ORDER_REQUEST = 'CONVERSATION_REQUEST';
// export const ORDER_REQUEST_SUCCESS = 'CONVERSATION_REQUEST_SUCCESS';
// export const ORDER_REQUEST_FAILURE = 'CONVERSATION_REQUEST_FAILURE';
// export const ORDER_RESTORE = 'ORDER_RESTORE';
// export const ORDER_RESTORE_FAILURE = 'ORDER_RESTORE_FAILURE';
// export const ORDER_RESTORE_SUCCESS = 'ORDER_RESTORE_SUCCESS';
// export const ORDER_SAVE = 'ORDER_SAVE';
// export const ORDER_SAVE_SUCCESS = 'ORDER_SAVE_SUCCESS';
// export const ORDER_SAVE_FAILURE = 'ORDER_SAVE_FAILURE';

// export const REALTIME_IO_CLOSE = 'REALTIME_IO_CLOSE';
// export const REALTIME_RECEIVE_USER = 'REALTIME_RECEIVE_USER';
// export const REALTIME_INIT_SITE_SOCKET = 'REALTIME_INIT_SITE_SOCKET';
// export const REALTIME_INIT_USER_SOCKET = 'REALTIME_INIT_USER_SOCKET';
// export const REALTIME_SEND_ROLE_SOCKET = 'REALTIME_SEND_ROLE_SOCKET';
// export const REALTIME_SEND_USER_SOCKET = 'REALTIME_SEND_USER_SOCKET';
// export const REALTIME_RECEIVE_LOGISTIC_DATA = 'REALTIME_RECEIVE_LOGISTIC_DATA';

// resltime orders
// export const REALTIME_ASSIGNED_ORDER = 'REALTIME_ASSIGNED_ORDER';

export const REQUEST_ME_INVITES = 'REQUEST_ME_INVITES';
export const REQUEST_ME_INVITES_SUCCESS = 'REQUEST_ME_INVITES_SUCCESS';
export const REQUEST_ME_INVITES_FAILURE = 'REQUEST_ME_INVITES_FAILURE';
export const RECEIVED_ME_INVITES = 'RECEIVED_ME_INVITES';

export const REQUEST_FACEBOOK_PAGES = 'REQUEST_FACEBOOK_PAGES';
export const RECEIVED_FACEBOOK_PAGES = 'RECEIVED_FACEBOOK_PAGES';
export const REQUEST_FACEBOOK_PAGES_SUCCESS = 'REQUEST_FACEBOOK_PAGES_SUCCESS';
export const REQUEST_FACEBOOK_PAGES_FAILED = 'REQUEST_FACEBOOK_PAGES_FAILED';
export const PAGES_RECEIVED = 'PAGES_RECEIVED';

export const FACEBOOK_INIT_PAGE_REQUEST = 'FACEBOOK_INIT_PAGE_REQUEST';
export const FACEBOOK_INIT_PAGE_SUCCESS = 'FACEBOOK_INIT_PAGE_SUCCESS';
export const FACEBOOK_INIT_PAGE_FAILURE = 'FACEBOOK_INIT_PAGE_FAILURE';
export const INIT_PAGE_START = 'INIT_PAGE_START';
export const INIT_PAGE_COMPLETE = 'INIT_PAGE_COMPLETE';

// export const CONVERSATION_GRAPH_FAILED = 'CONVERSATION_GRAPH_FAILED';
// export const CONVERSATION_CONVERSATION_REQUEST = 'CONVERSATION_CONVERSATION_REQUEST';
// export const CONVERSATION_CONVERSATION_REQUEST_FAILED = 'CONVERSATION_CONVERSATION_REQUEST_FAILED';
// export const CONVERSATION_CONVERSATION_REQUEST_SUCCESS = 'CONVERSATION_CONVERSATION_REQUEST_SUCCESS';
// export const CONVERSATION_CONVERSATION_RECEIVED = 'CONVERSATION_CONVERSATION_RECEIVED';

// export const CONVERSATION_SET_CURRENT_MESSAGE = 'CONVERSATION_SET_CURRENT_MESSAGE';
// export const CONVERSATION_SEND_TYPING = 'CONVERSATION_SEND_TYPING';
// export const CONVERSATION_SEND_NOT_TYPING = 'CONVERSATION_SEND_NOT_TYPING';
// export const CONVERSATION_TYPE_RECEIVED = 'CONVERSATION_TYPE_RECEIVED';
// export const CONVERSATION_SOURCE_RECEIVED = 'CONVERSATION_SOURCE_RECEIVED';
// export const CONVERSATION_COMMENTS_RECEIVED = 'CONVERSATION_COMMENTS_RECEIVED';
// export const CONVERSATION_COMMENTS_REQUEST_FAILURED = 'CONVERSATION_COMMENTS_REQUEST_FAILURED';
// export const CONVERSATION_MESSAGES_REQUEST = 'CONVERSATION_MESSAGES_REQUEST';
// export const CONVERSATION_MESSAGES_RECEIVED = 'CONVERSATION_MESSAGES_RECEIVED';
// export const CONVERSATION_MESSAGES_REQUEST_FAILURED = 'CONVERSATION_MESSAGES_REQUEST_FAILURED';
// export const CONVERSATION_MESSAGES_REQUEST_SUCCESS = 'CONVERSATION_MESSAGES_REQUEST_SUCCESS';

export const REQUEST_ACTIVED_PAGES = 'REQUEST_ACTIVED_PAGES';
export const RECEIVED_ACTIVED_PAGES = 'RECEIVED_ACTIVED_PAGES';
export const REQUEST_ACTIVED_PAGES_FAILURED = 'REQUEST_ACTIVED_PAGES_FAILURED';
export const REQUEST_ACTIVED_PAGES_SUCCESS = 'REQUEST_ACTIVED_PAGES_SUCCESS';

// CONVERSATIONS

export const SELECTED_PAGE_SET = 'SELECTED_PAGE_SET';
export const CONVERSATIONS_RECEIVE = 'CONVERSATIONS_RECEIVE';
export const CONVERSATIONS_REQUEST = 'CONVERSATIONS_REQUEST';
export const CONVERSATIONS_REQUEST_FAILURE = 'CONVERSATIONS_REQUEST_FAILURE';
export const CONVERSATIONS_REQUEST_SUCCESS = 'CONVERSATIONS_REQUEST_SUCCESS';
// export const CONVERSATION_COUNTS_RECEIVE = 'CONVERSATION_COUNTS_RECEIVE';
// export const CONVERSATION_COUNTS_REQUEST = 'CONVERSATION_COUNTS_REQUEST';
// export const CONVERSATION_COUNTS_REQUEST_FAILURE = 'CONVERSATION_COUNTS_REQUEST_FAILURE';
// export const CONVERSATION_COUNTS_REQUEST_SUCCESS = 'CONVERSATION_COUNTS_REQUEST_SUCCESS';
// export const CONVERSATION_COUNTS_RESET_INTERNAL_STATE = 'CONVERSATION_COUNTS_RESET_INTERNAL_STATE';
// export const CONVERSATION_DELETE = 'CONVERSATION_DELETE';
// export const CONVERSATION_DELETE_FAILURE = 'CONVERSATION_DELETE_FAILURE';
// export const CONVERSATION_DELETE_SUCCESS = 'CONVERSATION_DELETE_SUCCESS';
// export const CONVERSATION_EDIT = 'CONVERSATION_EDIT';
// export const CONVERSATION_FORMATS_RECEIVE = 'CONVERSATION_FORMATS_RECEIVE';
// export const CONVERSATION_FORMATS_REQUEST = 'CONVERSATION_FORMATS_REQUEST';
// export const CONVERSATION_FORMATS_REQUEST_FAILURE = 'CONVERSATION_FORMATS_REQUEST_FAILURE';
// export const CONVERSATION_FORMATS_REQUEST_SUCCESS = 'CONVERSATION_FORMATS_REQUEST_SUCCESS';
// export const CONVERSATION_LIKE = 'CONVERSATION_LIKE';
// export const CONVERSATION_LIKES_ADD_LIKER = 'CONVERSATION_LIKES_ADD_LIKER';
// export const CONVERSATION_LIKES_RECEIVE = 'CONVERSATION_LIKES_RECEIVE';
// export const CONVERSATION_LIKES_REMOVE_LIKER = 'CONVERSATION_LIKES_REMOVE_LIKER';
// export const CONVERSATION_LIKES_REQUEST = 'CONVERSATION_LIKES_REQUEST';
// need re-write
// export const CONVERSATION_REQUESTS = 'CONVERSATION_REQUESTS';
// export const CONVERSATION_REQUESTS_FAILURE = 'CONVERSATION_REQUESTS_FAILURE';
// export const CONVERSATION_REQUESTS_SUCCESS = 'CONVERSATION_REQUESTS_SUCCESS';

// export const CONVERSATION_REQUEST_MORE = 'CONVERSATION_REQUEST_MORE';
// export const CONVERSATION_REQUEST_MORE_SUCCESS = 'CONVERSATION_REQUEST_MORE_SUCCESS';
// export const CONVERSATION_REQUEST_MORE_FAILURED = 'CONVERSATION_REQUEST_MORE_FAILURED';
// export const CONVERSATION_RECEIVED_MORE = 'CONVERSATION_RECEIVED_MORE';

// export const CONVERSATION_RESTORE = 'CONVERSATION_RESTORE';
// export const CONVERSATION_RESTORE_FAILURE = 'CONVERSATION_RESTORE_FAILURE';
// export const CONVERSATION_RESTORE_SUCCESS = 'CONVERSATION_RESTORE_SUCCESS';
// export const CONVERSATION_REVISIONS_DIALOG_CLOSE = 'CONVERSATION_REVISIONS_DIALOG_CLOSE';
// export const CONVERSATION_REVISIONS_DIALOG_OPEN = 'CONVERSATION_REVISIONS_DIALOG_OPEN';
// export const CONVERSATION_REVISIONS_RECEIVE = 'CONVERSATION_REVISIONS_RECEIVE';
// export const CONVERSATION_REVISIONS_REQUEST = 'CONVERSATION_REVISIONS_REQUEST';
// export const CONVERSATION_REVISIONS_REQUEST_FAILURE = 'CONVERSATION_REVISIONS_REQUEST_FAILURE';
// export const CONVERSATION_REVISIONS_REQUEST_SUCCESS = 'CONVERSATION_REVISIONS_REQUEST_SUCCESS';
// export const CONVERSATION_REVISIONS_SELECT = 'CONVERSATION_REVISIONS_SELECT';
// export const CONVERSATION_SAVE = 'CONVERSATION_SAVE';
// export const CONVERSATION_SAVE_FAILURE = 'CONVERSATION_SAVE_FAILURE';
// export const CONVERSATION_SAVE_SUCCESS = 'CONVERSATION_SAVE_SUCCESS';
// export const CONVERSATION_STATS_RECEIVE = 'CONVERSATION_STATS_RECEIVE';
// export const CONVERSATION_STATS_REQUEST = 'CONVERSATION_STATS_REQUEST';
// export const CONVERSATION_STATS_REQUEST_FAILURE = 'CONVERSATION_STATS_REQUEST_FAILURE';
// export const CONVERSATION_STATS_REQUEST_SUCCESS = 'CONVERSATION_STATS_REQUEST_SUCCESS';
// export const CONVERSATION_TYPE_LIST_LIKES_POPOVER_HIDE = 'CONVERSATION_TYPE_LIST_LIKES_POPOVER_HIDE';
// export const CONVERSATION_TYPE_LIST_LIKES_POPOVER_TOGGLE = 'CONVERSATION_TYPE_LIST_LIKES_POPOVER_TOGGLE';
// export const CONVERSATION_TYPE_LIST_MULTI_SELECTION_MODE_TOGGLE =
// 	'CONVERSATION_TYPE_LIST_MULTI_SELECTION_MODE_TOGGLE';
// 	export const CONVERSATION_TYPE_LIST_MULTI_SELECTION_MODE_ACTIVE =
// 	'CONVERSATION_TYPE_LIST_MULTI_SELECTION_MODE_ACTIVE';
// export const CONVERSATION_TYPE_LIST_SELECTION_TOGGLE = 'CONVERSATION_TYPE_LIST_SELECTION_TOGGLE';
// export const CONVERSATION_TYPE_LIST_SHARE_PANEL_HIDE = 'CONVERSATION_TYPE_LIST_SHARE_PANEL_HIDE';
// export const CONVERSATION_TYPE_LIST_SHARE_PANEL_TOGGLE = 'CONVERSATION_TYPE_LIST_SHARE_PANEL_TOGGLE';
// export const CONVERSATION_TYPES_RECEIVE = 'CONVERSATION_TYPES_RECEIVE';
// export const CONVERSATION_TYPES_REQUEST = 'CONVERSATION_TYPES_REQUEST';

export const CONVERSATION_LIST_SELECTION_TOGGLE = 'CONVERSATION_LIST_SELECTION_TOGGLE';

export const CONVERSATION_REQUEST = 'CONVERSATION_REQUEST';
export const CONVERSATION_RECEIVED = 'CONVERSATION_RECEIVED';
export const CONVERSATION_REQUEST_FAILURED = 'CONVERSATION_REQUEST_FAILURED';
export const CONVERSATION_REQUEST_SUCCESS = 'CONVERSATION_REQUEST_SUCCESS';

export const CONVERSATION_REQUEST_MORE = 'CONVERSATION_REQUEST_MORE';
export const CONVERSATION_REQUEST_MORE_SUCCESS = 'CONVERSATION_REQUEST_MORE_SUCCESS';
export const CONVERSATION_REQUEST_MORE_FAILURED = 'CONVERSATION_REQUEST_MORE_FAILURED';
export const CONVERSATION_RECEIVED_MORE = 'CONVERSATION_RECEIVED_MORE';

export const CURRENT_PAGE_CHANGED = 'CURRENT_PAGE_CHANGED';

// conversation
export const RECEIVED_PENDING_MESSAGE = 'RECEIVED_PENDING_MESSAGE';
export const RECEIVED_MORE_MESSAGES = 'RECEIVED_MORE_MESSAGES'; // in case of load more messages in a conversation
export const CONVERSATION_DETAIL_RECEIVED = 'CONVERSATION_DETAIL_RECEIVED';

// page settings
export const REQUEST_PAGES_SETTINGS = 'REQUEST_PAGES_SETTINGS';
export const REQUEST_PAGES_SETTINGS_FAILURED = 'REQUEST_PAGES_SETTINGS_FAILURED';
export const REQUEST_PAGES_SETTINGS_SUCCESS = 'REQUEST_PAGES_SETTINGS_SUCCESS';
export const RECEIVED_PAGES_SETTINGS = 'RECEIVED_PAGES_SETTINGS';

export const CREATE_PAGE_SNIPPET = 'CREATE_PAGE_SNIPPET';
export const CREATE_PAGE_SNIPPET_SUCCESS = 'CREATE_PAGE_SNIPPET_SUCCESS';
export const CREATE_PAGE_SNIPPET_FAILURED = 'CREATE_PAGE_SNIPPET_FAILURED';
export const RECEIVED_PAGE_SNIPPET = 'RECEIVED_PAGE_SNIPPET';
export const REQUEST_PAGE_REPLY_SNIPESTS = 'REQUEST_PAGE_REPLY_SNIPESTS';
export const REQUEST_PAGE_REPLY_SNIPESTS_FAILURED = 'REQUEST_PAGE_REPLY_SNIPESTS_FAILURED';
export const REQUEST_PAGE_REPLY_SNIPESTS_SUCCESS = 'REQUEST_PAGE_REPLY_SNIPESTS_SUCCESS';
export const RECEIVED_PAGE_REPLY_SNIPESTS = 'RECEIVED_PAGE_REPLY_SNIPESTS';
export const REQUEST_UPDATE_PAGE_SNIPPET = 'REQUEST_UPDATE_PAGE_SNIPPET';
export const UPDATE_PAGE_SNIPPET_SUCCESS = 'UPDATE_PAGE_SNIPPET_SUCCESS';
export const UPDATE_PAGE_SNIPPET_FAILURED = 'UPDATE_PAGE_SNIPPET_FAILURED';
export const RECEIVED_PAGE_SNIPPET_UPDATE = 'RECEIVED_PAGE_SNIPPET_UPDATE';

export const CREATE_AUTO_MESSAGE_TASK = 'CREATE_AUTO_MESSAGE_TASK';
export const CREATE_AUTO_MESSAGE_TASK_SUCCESS = 'CREATE_AUTO_MESSAGE_TASK_SUCCESS';
export const CREATE_AUTO_MESSAGE_TASK_FAILURED = 'CREATE_AUTO_MESSAGE_TASK_FAILURED';
export const RECEIVED_AUTO_MESSAGE_TASK = 'RECEIVED_AUTO_MESSAGE_TASK';

export const REQUEST_AUTO_MESSAGE_TASKS = 'REQUEST_AUTO_MESSAGE_TASKS';
export const REQUEST_AUTO_MESSAGE_TASKS_SUCCESS = 'REQUEST_AUTO_MESSAGE_TASKS_SUCCESS';
export const REQUEST_AUTO_MESSAGE_TASKS_FAILURED = 'REQUEST_AUTO_MESSAGE_TASKS_FAILURED';
export const RECEIVED_AUTO_MESSAGE_TASKS = 'RECEIVED_AUTO_MESSAGE_TASKS';

export const RECEIVED_PAGE_TAGS = 'RECEIVED_PAGE_TAGS';
export const REQUEST_PAGE_TAGS = 'REQUEST_PAGE_TAGS';
export const REQUEST_PAGE_TAGS_SUCCESS = 'REQUEST_PAGE_TAGS_SUCCESS';
export const REQUEST_PAGE_TAGS_FAILURED = 'REQUEST_PAGE_TAGS_FAILURED';

export const ADD_NEW_PAGE_TAG = 'ADD_NEW_PAGE_TAG';
export const ADD_NEW_PAGE_TAG_SUCCESS = 'ADD_NEW_PAGE_TAG_SUCCESS';
export const RECEIVED_NEW_PAGE_TAG = 'RECEIVED_NEW_PAGE_TAG';
export const ADD_NEW_PAGE_TAG_FAILURED = 'ADD_NEW_PAGE_TAG_FAILURED';

export const REQUEST_PREFERENCES = 'REQUEST_PREFERENCES';
export const REQUEST_PREFERENCES_SUCCESS = 'REQUEST_PREFERENCES_SUCCESS';
export const REQUEST_PREFERENCES_FAILURED = 'REQUEST_PREFERENCES_FAILURED';
export const RECEIVED_PREFERENCES = 'RECEIVED_PREFERENCES';
export const UPDATE_COMPOSER_SUGGESTION_DISPLAY = 'UPDATE_COMPOSER_SUGGESTION_DISPLAY';

export const ON_SWITCH_PAGE = 'ON_SWITCH_PAGE';

export const ADD_TAG_TO_CONVERSATION = 'ADD_TAG_TO_CONVERSATION';
export const ADD_TAG_TO_CONVERSATION_FAILURED = 'ADD_TAG_TO_CONVERSATION_FAILURED';
export const ADD_TAG_TO_CONVERSATION_SUCCESS = 'ADD_TAG_TO_CONVERSATION_SUCCESS';
export const CONVERSATION_RECEIVED_TAG = 'CONVERSATION_RECEIVED_TAG';
export const CONVERSATION_REMOVED_TAG = 'CONVERSATION_REMOVED_TAG';

export const RECEIVED_CONVERSATION_SEEN = 'RECEIVED_CONVERSATION_SEEN';
export const RECEIVED_CONVERSATION_UNSEEN = 'RECEIVED_CONVERSATION_UNSEEN';

export const ON_PREVENT_SEND_MESSAGE = 'ON_PREVENT_SEND_MESSAGE';

export const CREATE_CONVERSATION_NOTE = 'CREATE_CONVERSATION_NOTE';
export const CREATE_CONVERSATION_NOTE_SUCCESS = 'CREATE_CONVERSATION_NOTE_SUCCESS';
export const CREATE_CONVERSATION_NOTE_FAILURED = 'CREATE_CONVERSATION_NOTE_FAILURED';
export const RECEIVED_CONVERSATION_NOTE = 'RECEIVED_CONVERSATION_NOTE';

export const REPLY_FACEBOOK_COMMENT_SUCCESS = 'REPLY_FACEBOOK_COMMENT_SUCCESS';
export const REPLY_FACEBOOK_COMMENT_FAILED = 'REPLY_FACEBOOK_COMMENT_FAILED';
export const DELETE_PENDING_MESSAGE = 'DELETE_PENDING_MESSAGE';

export const RECEIVED_CONVERSATION_UPDATED = 'RECEIVED_CONVERSATION_UPDATED';
export const RECEIVED_CONVERSATION_MESSAGE = 'RECEIVED_CONVERSATION_MESSAGE';
export const CHANGE_SELECTED_CONVERSATION = 'CHANGE_SELECTED_CONVERSATION';

export const RECEIVED_PAGE_STATUS_UPDATED = 'RECEIVED_PAGE_STATUS_UPDATED';
export const RECEIVED_PAGES_STATUS_UPDATED = 'RECEIVED_PAGES_STATUS_UPDATED';
export const RECEIVED_PAGE_INIT_VALIDATION = 'RECEIVED_PAGE_INIT_VALIDATION';
export const RECEIVED_PAGE_INIT_VALUE = 'RECEIVED_PAGE_INIT_VALUE';
